// Code generated by go-swagger; DO NOT EDIT.

package authentication_user_role_mapping_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteUserMappingGivenVmidUsingDELETEReader is a Reader for the DeleteUserMappingGivenVmidUsingDELETE structure.
type DeleteUserMappingGivenVmidUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserMappingGivenVmidUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUserMappingGivenVmidUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteUserMappingGivenVmidUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteUserMappingGivenVmidUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteUserMappingGivenVmidUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUserMappingGivenVmidUsingDELETEOK creates a DeleteUserMappingGivenVmidUsingDELETEOK with default headers values
func NewDeleteUserMappingGivenVmidUsingDELETEOK() *DeleteUserMappingGivenVmidUsingDELETEOK {
	return &DeleteUserMappingGivenVmidUsingDELETEOK{}
}

/*DeleteUserMappingGivenVmidUsingDELETEOK handles this case with default header values.

OK
*/
type DeleteUserMappingGivenVmidUsingDELETEOK struct {
	Payload interface{}
}

func (o *DeleteUserMappingGivenVmidUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/userrolemapping/{vmid}][%d] deleteUserMappingGivenVmidUsingDELETEOK  %+v", 200, o.Payload)
}

func (o *DeleteUserMappingGivenVmidUsingDELETEOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteUserMappingGivenVmidUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUserMappingGivenVmidUsingDELETENoContent creates a DeleteUserMappingGivenVmidUsingDELETENoContent with default headers values
func NewDeleteUserMappingGivenVmidUsingDELETENoContent() *DeleteUserMappingGivenVmidUsingDELETENoContent {
	return &DeleteUserMappingGivenVmidUsingDELETENoContent{}
}

/*DeleteUserMappingGivenVmidUsingDELETENoContent handles this case with default header values.

No Content
*/
type DeleteUserMappingGivenVmidUsingDELETENoContent struct {
}

func (o *DeleteUserMappingGivenVmidUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/userrolemapping/{vmid}][%d] deleteUserMappingGivenVmidUsingDELETENoContent ", 204)
}

func (o *DeleteUserMappingGivenVmidUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserMappingGivenVmidUsingDELETEUnauthorized creates a DeleteUserMappingGivenVmidUsingDELETEUnauthorized with default headers values
func NewDeleteUserMappingGivenVmidUsingDELETEUnauthorized() *DeleteUserMappingGivenVmidUsingDELETEUnauthorized {
	return &DeleteUserMappingGivenVmidUsingDELETEUnauthorized{}
}

/*DeleteUserMappingGivenVmidUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteUserMappingGivenVmidUsingDELETEUnauthorized struct {
}

func (o *DeleteUserMappingGivenVmidUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/userrolemapping/{vmid}][%d] deleteUserMappingGivenVmidUsingDELETEUnauthorized ", 401)
}

func (o *DeleteUserMappingGivenVmidUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserMappingGivenVmidUsingDELETEForbidden creates a DeleteUserMappingGivenVmidUsingDELETEForbidden with default headers values
func NewDeleteUserMappingGivenVmidUsingDELETEForbidden() *DeleteUserMappingGivenVmidUsingDELETEForbidden {
	return &DeleteUserMappingGivenVmidUsingDELETEForbidden{}
}

/*DeleteUserMappingGivenVmidUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type DeleteUserMappingGivenVmidUsingDELETEForbidden struct {
}

func (o *DeleteUserMappingGivenVmidUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/userrolemapping/{vmid}][%d] deleteUserMappingGivenVmidUsingDELETEForbidden ", 403)
}

func (o *DeleteUserMappingGivenVmidUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
