// Code generated by go-swagger; DO NOT EDIT.

package authentication_user_role_mapping_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetUserRoleMappingGivenRoleIDUsingGETReader is a Reader for the GetUserRoleMappingGivenRoleIDUsingGET structure.
type GetUserRoleMappingGivenRoleIDUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserRoleMappingGivenRoleIDUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserRoleMappingGivenRoleIDUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetUserRoleMappingGivenRoleIDUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetUserRoleMappingGivenRoleIDUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUserRoleMappingGivenRoleIDUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserRoleMappingGivenRoleIDUsingGETOK creates a GetUserRoleMappingGivenRoleIDUsingGETOK with default headers values
func NewGetUserRoleMappingGivenRoleIDUsingGETOK() *GetUserRoleMappingGivenRoleIDUsingGETOK {
	return &GetUserRoleMappingGivenRoleIDUsingGETOK{}
}

/*GetUserRoleMappingGivenRoleIDUsingGETOK handles this case with default header values.

OK
*/
type GetUserRoleMappingGivenRoleIDUsingGETOK struct {
	Payload interface{}
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/userrolemapping/roleId/{rolevmid}][%d] getUserRoleMappingGivenRoleIdUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserRoleMappingGivenRoleIDUsingGETUnauthorized creates a GetUserRoleMappingGivenRoleIDUsingGETUnauthorized with default headers values
func NewGetUserRoleMappingGivenRoleIDUsingGETUnauthorized() *GetUserRoleMappingGivenRoleIDUsingGETUnauthorized {
	return &GetUserRoleMappingGivenRoleIDUsingGETUnauthorized{}
}

/*GetUserRoleMappingGivenRoleIDUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetUserRoleMappingGivenRoleIDUsingGETUnauthorized struct {
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/userrolemapping/roleId/{rolevmid}][%d] getUserRoleMappingGivenRoleIdUsingGETUnauthorized ", 401)
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserRoleMappingGivenRoleIDUsingGETForbidden creates a GetUserRoleMappingGivenRoleIDUsingGETForbidden with default headers values
func NewGetUserRoleMappingGivenRoleIDUsingGETForbidden() *GetUserRoleMappingGivenRoleIDUsingGETForbidden {
	return &GetUserRoleMappingGivenRoleIDUsingGETForbidden{}
}

/*GetUserRoleMappingGivenRoleIDUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetUserRoleMappingGivenRoleIDUsingGETForbidden struct {
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/userrolemapping/roleId/{rolevmid}][%d] getUserRoleMappingGivenRoleIdUsingGETForbidden ", 403)
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserRoleMappingGivenRoleIDUsingGETNotFound creates a GetUserRoleMappingGivenRoleIDUsingGETNotFound with default headers values
func NewGetUserRoleMappingGivenRoleIDUsingGETNotFound() *GetUserRoleMappingGivenRoleIDUsingGETNotFound {
	return &GetUserRoleMappingGivenRoleIDUsingGETNotFound{}
}

/*GetUserRoleMappingGivenRoleIDUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetUserRoleMappingGivenRoleIDUsingGETNotFound struct {
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/userrolemapping/roleId/{rolevmid}][%d] getUserRoleMappingGivenRoleIdUsingGETNotFound ", 404)
}

func (o *GetUserRoleMappingGivenRoleIDUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
