// Code generated by go-swagger; DO NOT EDIT.

package authentication_user_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteUserByIDUsingDELETEReader is a Reader for the DeleteUserByIDUsingDELETE structure.
type DeleteUserByIDUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserByIDUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUserByIDUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteUserByIDUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteUserByIDUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteUserByIDUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUserByIDUsingDELETEOK creates a DeleteUserByIDUsingDELETEOK with default headers values
func NewDeleteUserByIDUsingDELETEOK() *DeleteUserByIDUsingDELETEOK {
	return &DeleteUserByIDUsingDELETEOK{}
}

/*DeleteUserByIDUsingDELETEOK handles this case with default header values.

OK
*/
type DeleteUserByIDUsingDELETEOK struct {
	Payload interface{}
}

func (o *DeleteUserByIDUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/users/{vmid}][%d] deleteUserByIdUsingDELETEOK  %+v", 200, o.Payload)
}

func (o *DeleteUserByIDUsingDELETEOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteUserByIDUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUserByIDUsingDELETENoContent creates a DeleteUserByIDUsingDELETENoContent with default headers values
func NewDeleteUserByIDUsingDELETENoContent() *DeleteUserByIDUsingDELETENoContent {
	return &DeleteUserByIDUsingDELETENoContent{}
}

/*DeleteUserByIDUsingDELETENoContent handles this case with default header values.

No Content
*/
type DeleteUserByIDUsingDELETENoContent struct {
}

func (o *DeleteUserByIDUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/users/{vmid}][%d] deleteUserByIdUsingDELETENoContent ", 204)
}

func (o *DeleteUserByIDUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserByIDUsingDELETEUnauthorized creates a DeleteUserByIDUsingDELETEUnauthorized with default headers values
func NewDeleteUserByIDUsingDELETEUnauthorized() *DeleteUserByIDUsingDELETEUnauthorized {
	return &DeleteUserByIDUsingDELETEUnauthorized{}
}

/*DeleteUserByIDUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteUserByIDUsingDELETEUnauthorized struct {
}

func (o *DeleteUserByIDUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/users/{vmid}][%d] deleteUserByIdUsingDELETEUnauthorized ", 401)
}

func (o *DeleteUserByIDUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserByIDUsingDELETEForbidden creates a DeleteUserByIDUsingDELETEForbidden with default headers values
func NewDeleteUserByIDUsingDELETEForbidden() *DeleteUserByIDUsingDELETEForbidden {
	return &DeleteUserByIDUsingDELETEForbidden{}
}

/*DeleteUserByIDUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type DeleteUserByIDUsingDELETEForbidden struct {
}

func (o *DeleteUserByIDUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /lcm/authzn/api/users/{vmid}][%d] deleteUserByIdUsingDELETEForbidden ", 403)
}

func (o *DeleteUserByIDUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
