// Code generated by go-swagger; DO NOT EDIT.

package content_lease_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCleanContentLeasesUsingDELETEParams creates a new CleanContentLeasesUsingDELETEParams object
// with the default values initialized.
func NewCleanContentLeasesUsingDELETEParams() *CleanContentLeasesUsingDELETEParams {

	return &CleanContentLeasesUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCleanContentLeasesUsingDELETEParamsWithTimeout creates a new CleanContentLeasesUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCleanContentLeasesUsingDELETEParamsWithTimeout(timeout time.Duration) *CleanContentLeasesUsingDELETEParams {

	return &CleanContentLeasesUsingDELETEParams{

		timeout: timeout,
	}
}

// NewCleanContentLeasesUsingDELETEParamsWithContext creates a new CleanContentLeasesUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewCleanContentLeasesUsingDELETEParamsWithContext(ctx context.Context) *CleanContentLeasesUsingDELETEParams {

	return &CleanContentLeasesUsingDELETEParams{

		Context: ctx,
	}
}

// NewCleanContentLeasesUsingDELETEParamsWithHTTPClient creates a new CleanContentLeasesUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCleanContentLeasesUsingDELETEParamsWithHTTPClient(client *http.Client) *CleanContentLeasesUsingDELETEParams {

	return &CleanContentLeasesUsingDELETEParams{
		HTTPClient: client,
	}
}

/*CleanContentLeasesUsingDELETEParams contains all the parameters to send to the API endpoint
for the clean content leases using d e l e t e operation typically these are written to a http.Request
*/
type CleanContentLeasesUsingDELETEParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the clean content leases using d e l e t e params
func (o *CleanContentLeasesUsingDELETEParams) WithTimeout(timeout time.Duration) *CleanContentLeasesUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the clean content leases using d e l e t e params
func (o *CleanContentLeasesUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the clean content leases using d e l e t e params
func (o *CleanContentLeasesUsingDELETEParams) WithContext(ctx context.Context) *CleanContentLeasesUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the clean content leases using d e l e t e params
func (o *CleanContentLeasesUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the clean content leases using d e l e t e params
func (o *CleanContentLeasesUsingDELETEParams) WithHTTPClient(client *http.Client) *CleanContentLeasesUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the clean content leases using d e l e t e params
func (o *CleanContentLeasesUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CleanContentLeasesUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
