// Code generated by go-swagger; DO NOT EDIT.

package application_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllApplicationsUsingGETParams creates a new GetAllApplicationsUsingGETParams object
// with the default values initialized.
func NewGetAllApplicationsUsingGETParams() *GetAllApplicationsUsingGETParams {

	return &GetAllApplicationsUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllApplicationsUsingGETParamsWithTimeout creates a new GetAllApplicationsUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllApplicationsUsingGETParamsWithTimeout(timeout time.Duration) *GetAllApplicationsUsingGETParams {

	return &GetAllApplicationsUsingGETParams{

		timeout: timeout,
	}
}

// NewGetAllApplicationsUsingGETParamsWithContext creates a new GetAllApplicationsUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllApplicationsUsingGETParamsWithContext(ctx context.Context) *GetAllApplicationsUsingGETParams {

	return &GetAllApplicationsUsingGETParams{

		Context: ctx,
	}
}

// NewGetAllApplicationsUsingGETParamsWithHTTPClient creates a new GetAllApplicationsUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllApplicationsUsingGETParamsWithHTTPClient(client *http.Client) *GetAllApplicationsUsingGETParams {

	return &GetAllApplicationsUsingGETParams{
		HTTPClient: client,
	}
}

/*GetAllApplicationsUsingGETParams contains all the parameters to send to the API endpoint
for the get all applications using g e t operation typically these are written to a http.Request
*/
type GetAllApplicationsUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all applications using g e t params
func (o *GetAllApplicationsUsingGETParams) WithTimeout(timeout time.Duration) *GetAllApplicationsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all applications using g e t params
func (o *GetAllApplicationsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all applications using g e t params
func (o *GetAllApplicationsUsingGETParams) WithContext(ctx context.Context) *GetAllApplicationsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all applications using g e t params
func (o *GetAllApplicationsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all applications using g e t params
func (o *GetAllApplicationsUsingGETParams) WithHTTPClient(client *http.Client) *GetAllApplicationsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all applications using g e t params
func (o *GetAllApplicationsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllApplicationsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
