// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewDeleteDirectoryUsingPOSTParams creates a new DeleteDirectoryUsingPOSTParams object
// with the default values initialized.
func NewDeleteDirectoryUsingPOSTParams() *DeleteDirectoryUsingPOSTParams {
	var ()
	return &DeleteDirectoryUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDirectoryUsingPOSTParamsWithTimeout creates a new DeleteDirectoryUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDirectoryUsingPOSTParamsWithTimeout(timeout time.Duration) *DeleteDirectoryUsingPOSTParams {
	var ()
	return &DeleteDirectoryUsingPOSTParams{

		timeout: timeout,
	}
}

// NewDeleteDirectoryUsingPOSTParamsWithContext creates a new DeleteDirectoryUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDirectoryUsingPOSTParamsWithContext(ctx context.Context) *DeleteDirectoryUsingPOSTParams {
	var ()
	return &DeleteDirectoryUsingPOSTParams{

		Context: ctx,
	}
}

// NewDeleteDirectoryUsingPOSTParamsWithHTTPClient creates a new DeleteDirectoryUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDirectoryUsingPOSTParamsWithHTTPClient(client *http.Client) *DeleteDirectoryUsingPOSTParams {
	var ()
	return &DeleteDirectoryUsingPOSTParams{
		HTTPClient: client,
	}
}

/*DeleteDirectoryUsingPOSTParams contains all the parameters to send to the API endpoint
for the delete directory using p o s t operation typically these are written to a http.Request
*/
type DeleteDirectoryUsingPOSTParams struct {

	/*VidmDirDeleteRequestDTO
	  vidmDirDeleteRequestDTO

	*/
	VidmDirDeleteRequestDTO *models.VidmDirDeleteRequestDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) WithTimeout(timeout time.Duration) *DeleteDirectoryUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) WithContext(ctx context.Context) *DeleteDirectoryUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) WithHTTPClient(client *http.Client) *DeleteDirectoryUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVidmDirDeleteRequestDTO adds the vidmDirDeleteRequestDTO to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) WithVidmDirDeleteRequestDTO(vidmDirDeleteRequestDTO *models.VidmDirDeleteRequestDTO) *DeleteDirectoryUsingPOSTParams {
	o.SetVidmDirDeleteRequestDTO(vidmDirDeleteRequestDTO)
	return o
}

// SetVidmDirDeleteRequestDTO adds the vidmDirDeleteRequestDTO to the delete directory using p o s t params
func (o *DeleteDirectoryUsingPOSTParams) SetVidmDirDeleteRequestDTO(vidmDirDeleteRequestDTO *models.VidmDirDeleteRequestDTO) {
	o.VidmDirDeleteRequestDTO = vidmDirDeleteRequestDTO
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDirectoryUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.VidmDirDeleteRequestDTO != nil {
		if err := r.SetBodyParam(o.VidmDirDeleteRequestDTO); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
