// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAllConnectorsUsingPOSTReader is a Reader for the GetAllConnectorsUsingPOST structure.
type GetAllConnectorsUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllConnectorsUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllConnectorsUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewGetAllConnectorsUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAllConnectorsUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAllConnectorsUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllConnectorsUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllConnectorsUsingPOSTOK creates a GetAllConnectorsUsingPOSTOK with default headers values
func NewGetAllConnectorsUsingPOSTOK() *GetAllConnectorsUsingPOSTOK {
	return &GetAllConnectorsUsingPOSTOK{}
}

/*GetAllConnectorsUsingPOSTOK handles this case with default header values.

OK
*/
type GetAllConnectorsUsingPOSTOK struct {
	Payload interface{}
}

func (o *GetAllConnectorsUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/connectors][%d] getAllConnectorsUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *GetAllConnectorsUsingPOSTOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetAllConnectorsUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllConnectorsUsingPOSTCreated creates a GetAllConnectorsUsingPOSTCreated with default headers values
func NewGetAllConnectorsUsingPOSTCreated() *GetAllConnectorsUsingPOSTCreated {
	return &GetAllConnectorsUsingPOSTCreated{}
}

/*GetAllConnectorsUsingPOSTCreated handles this case with default header values.

Created
*/
type GetAllConnectorsUsingPOSTCreated struct {
}

func (o *GetAllConnectorsUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/connectors][%d] getAllConnectorsUsingPOSTCreated ", 201)
}

func (o *GetAllConnectorsUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllConnectorsUsingPOSTUnauthorized creates a GetAllConnectorsUsingPOSTUnauthorized with default headers values
func NewGetAllConnectorsUsingPOSTUnauthorized() *GetAllConnectorsUsingPOSTUnauthorized {
	return &GetAllConnectorsUsingPOSTUnauthorized{}
}

/*GetAllConnectorsUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAllConnectorsUsingPOSTUnauthorized struct {
}

func (o *GetAllConnectorsUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/connectors][%d] getAllConnectorsUsingPOSTUnauthorized ", 401)
}

func (o *GetAllConnectorsUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllConnectorsUsingPOSTForbidden creates a GetAllConnectorsUsingPOSTForbidden with default headers values
func NewGetAllConnectorsUsingPOSTForbidden() *GetAllConnectorsUsingPOSTForbidden {
	return &GetAllConnectorsUsingPOSTForbidden{}
}

/*GetAllConnectorsUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type GetAllConnectorsUsingPOSTForbidden struct {
}

func (o *GetAllConnectorsUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/connectors][%d] getAllConnectorsUsingPOSTForbidden ", 403)
}

func (o *GetAllConnectorsUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllConnectorsUsingPOSTNotFound creates a GetAllConnectorsUsingPOSTNotFound with default headers values
func NewGetAllConnectorsUsingPOSTNotFound() *GetAllConnectorsUsingPOSTNotFound {
	return &GetAllConnectorsUsingPOSTNotFound{}
}

/*GetAllConnectorsUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type GetAllConnectorsUsingPOSTNotFound struct {
}

func (o *GetAllConnectorsUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/connectors][%d] getAllConnectorsUsingPOSTNotFound ", 404)
}

func (o *GetAllConnectorsUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
