// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDirectoryDetailsUsingPOSTReader is a Reader for the GetDirectoryDetailsUsingPOST structure.
type GetDirectoryDetailsUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDirectoryDetailsUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDirectoryDetailsUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewGetDirectoryDetailsUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetDirectoryDetailsUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDirectoryDetailsUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDirectoryDetailsUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDirectoryDetailsUsingPOSTOK creates a GetDirectoryDetailsUsingPOSTOK with default headers values
func NewGetDirectoryDetailsUsingPOSTOK() *GetDirectoryDetailsUsingPOSTOK {
	return &GetDirectoryDetailsUsingPOSTOK{}
}

/*GetDirectoryDetailsUsingPOSTOK handles this case with default header values.

OK
*/
type GetDirectoryDetailsUsingPOSTOK struct {
	Payload interface{}
}

func (o *GetDirectoryDetailsUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/get][%d] getDirectoryDetailsUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *GetDirectoryDetailsUsingPOSTOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDirectoryDetailsUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDirectoryDetailsUsingPOSTCreated creates a GetDirectoryDetailsUsingPOSTCreated with default headers values
func NewGetDirectoryDetailsUsingPOSTCreated() *GetDirectoryDetailsUsingPOSTCreated {
	return &GetDirectoryDetailsUsingPOSTCreated{}
}

/*GetDirectoryDetailsUsingPOSTCreated handles this case with default header values.

Created
*/
type GetDirectoryDetailsUsingPOSTCreated struct {
}

func (o *GetDirectoryDetailsUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/get][%d] getDirectoryDetailsUsingPOSTCreated ", 201)
}

func (o *GetDirectoryDetailsUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDirectoryDetailsUsingPOSTUnauthorized creates a GetDirectoryDetailsUsingPOSTUnauthorized with default headers values
func NewGetDirectoryDetailsUsingPOSTUnauthorized() *GetDirectoryDetailsUsingPOSTUnauthorized {
	return &GetDirectoryDetailsUsingPOSTUnauthorized{}
}

/*GetDirectoryDetailsUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type GetDirectoryDetailsUsingPOSTUnauthorized struct {
}

func (o *GetDirectoryDetailsUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/get][%d] getDirectoryDetailsUsingPOSTUnauthorized ", 401)
}

func (o *GetDirectoryDetailsUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDirectoryDetailsUsingPOSTForbidden creates a GetDirectoryDetailsUsingPOSTForbidden with default headers values
func NewGetDirectoryDetailsUsingPOSTForbidden() *GetDirectoryDetailsUsingPOSTForbidden {
	return &GetDirectoryDetailsUsingPOSTForbidden{}
}

/*GetDirectoryDetailsUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type GetDirectoryDetailsUsingPOSTForbidden struct {
}

func (o *GetDirectoryDetailsUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/get][%d] getDirectoryDetailsUsingPOSTForbidden ", 403)
}

func (o *GetDirectoryDetailsUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDirectoryDetailsUsingPOSTNotFound creates a GetDirectoryDetailsUsingPOSTNotFound with default headers values
func NewGetDirectoryDetailsUsingPOSTNotFound() *GetDirectoryDetailsUsingPOSTNotFound {
	return &GetDirectoryDetailsUsingPOSTNotFound{}
}

/*GetDirectoryDetailsUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type GetDirectoryDetailsUsingPOSTNotFound struct {
}

func (o *GetDirectoryDetailsUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/get][%d] getDirectoryDetailsUsingPOSTNotFound ", 404)
}

func (o *GetDirectoryDetailsUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
