// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewGetAllConnectorsUsingPOSTParams creates a new GetAllConnectorsUsingPOSTParams object
// with the default values initialized.
func NewGetAllConnectorsUsingPOSTParams() *GetAllConnectorsUsingPOSTParams {
	var ()
	return &GetAllConnectorsUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllConnectorsUsingPOSTParamsWithTimeout creates a new GetAllConnectorsUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllConnectorsUsingPOSTParamsWithTimeout(timeout time.Duration) *GetAllConnectorsUsingPOSTParams {
	var ()
	return &GetAllConnectorsUsingPOSTParams{

		timeout: timeout,
	}
}

// NewGetAllConnectorsUsingPOSTParamsWithContext creates a new GetAllConnectorsUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllConnectorsUsingPOSTParamsWithContext(ctx context.Context) *GetAllConnectorsUsingPOSTParams {
	var ()
	return &GetAllConnectorsUsingPOSTParams{

		Context: ctx,
	}
}

// NewGetAllConnectorsUsingPOSTParamsWithHTTPClient creates a new GetAllConnectorsUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllConnectorsUsingPOSTParamsWithHTTPClient(client *http.Client) *GetAllConnectorsUsingPOSTParams {
	var ()
	return &GetAllConnectorsUsingPOSTParams{
		HTTPClient: client,
	}
}

/*GetAllConnectorsUsingPOSTParams contains all the parameters to send to the API endpoint
for the get all connectors using p o s t operation typically these are written to a http.Request
*/
type GetAllConnectorsUsingPOSTParams struct {

	/*VidmHostBaseDTO
	  vidmHostBaseDTO

	*/
	VidmHostBaseDTO *models.VidmHostBaseDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) WithTimeout(timeout time.Duration) *GetAllConnectorsUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) WithContext(ctx context.Context) *GetAllConnectorsUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) WithHTTPClient(client *http.Client) *GetAllConnectorsUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVidmHostBaseDTO adds the vidmHostBaseDTO to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) WithVidmHostBaseDTO(vidmHostBaseDTO *models.VidmHostBaseDTO) *GetAllConnectorsUsingPOSTParams {
	o.SetVidmHostBaseDTO(vidmHostBaseDTO)
	return o
}

// SetVidmHostBaseDTO adds the vidmHostBaseDTO to the get all connectors using p o s t params
func (o *GetAllConnectorsUsingPOSTParams) SetVidmHostBaseDTO(vidmHostBaseDTO *models.VidmHostBaseDTO) {
	o.VidmHostBaseDTO = vidmHostBaseDTO
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllConnectorsUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.VidmHostBaseDTO != nil {
		if err := r.SetBodyParam(o.VidmHostBaseDTO); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
