// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewTestConnectionUsingPOSTParams creates a new TestConnectionUsingPOSTParams object
// with the default values initialized.
func NewTestConnectionUsingPOSTParams() *TestConnectionUsingPOSTParams {
	var ()
	return &TestConnectionUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestConnectionUsingPOSTParamsWithTimeout creates a new TestConnectionUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestConnectionUsingPOSTParamsWithTimeout(timeout time.Duration) *TestConnectionUsingPOSTParams {
	var ()
	return &TestConnectionUsingPOSTParams{

		timeout: timeout,
	}
}

// NewTestConnectionUsingPOSTParamsWithContext creates a new TestConnectionUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestConnectionUsingPOSTParamsWithContext(ctx context.Context) *TestConnectionUsingPOSTParams {
	var ()
	return &TestConnectionUsingPOSTParams{

		Context: ctx,
	}
}

// NewTestConnectionUsingPOSTParamsWithHTTPClient creates a new TestConnectionUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTestConnectionUsingPOSTParamsWithHTTPClient(client *http.Client) *TestConnectionUsingPOSTParams {
	var ()
	return &TestConnectionUsingPOSTParams{
		HTTPClient: client,
	}
}

/*TestConnectionUsingPOSTParams contains all the parameters to send to the API endpoint
for the test connection using p o s t operation typically these are written to a http.Request
*/
type TestConnectionUsingPOSTParams struct {

	/*VidmDirConfigRequestDTO
	  vidmDirConfigRequestDTO

	*/
	VidmDirConfigRequestDTO *models.VidmDirConfigRequestDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) WithTimeout(timeout time.Duration) *TestConnectionUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) WithContext(ctx context.Context) *TestConnectionUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) WithHTTPClient(client *http.Client) *TestConnectionUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVidmDirConfigRequestDTO adds the vidmDirConfigRequestDTO to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) WithVidmDirConfigRequestDTO(vidmDirConfigRequestDTO *models.VidmDirConfigRequestDTO) *TestConnectionUsingPOSTParams {
	o.SetVidmDirConfigRequestDTO(vidmDirConfigRequestDTO)
	return o
}

// SetVidmDirConfigRequestDTO adds the vidmDirConfigRequestDTO to the test connection using p o s t params
func (o *TestConnectionUsingPOSTParams) SetVidmDirConfigRequestDTO(vidmDirConfigRequestDTO *models.VidmDirConfigRequestDTO) {
	o.VidmDirConfigRequestDTO = vidmDirConfigRequestDTO
}

// WriteToRequest writes these params to a swagger request
func (o *TestConnectionUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.VidmDirConfigRequestDTO != nil {
		if err := r.SetBodyParam(o.VidmDirConfigRequestDTO); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
