// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewTriggerDryrunUsingPOSTParams creates a new TriggerDryrunUsingPOSTParams object
// with the default values initialized.
func NewTriggerDryrunUsingPOSTParams() *TriggerDryrunUsingPOSTParams {
	var ()
	return &TriggerDryrunUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTriggerDryrunUsingPOSTParamsWithTimeout creates a new TriggerDryrunUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTriggerDryrunUsingPOSTParamsWithTimeout(timeout time.Duration) *TriggerDryrunUsingPOSTParams {
	var ()
	return &TriggerDryrunUsingPOSTParams{

		timeout: timeout,
	}
}

// NewTriggerDryrunUsingPOSTParamsWithContext creates a new TriggerDryrunUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewTriggerDryrunUsingPOSTParamsWithContext(ctx context.Context) *TriggerDryrunUsingPOSTParams {
	var ()
	return &TriggerDryrunUsingPOSTParams{

		Context: ctx,
	}
}

// NewTriggerDryrunUsingPOSTParamsWithHTTPClient creates a new TriggerDryrunUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTriggerDryrunUsingPOSTParamsWithHTTPClient(client *http.Client) *TriggerDryrunUsingPOSTParams {
	var ()
	return &TriggerDryrunUsingPOSTParams{
		HTTPClient: client,
	}
}

/*TriggerDryrunUsingPOSTParams contains all the parameters to send to the API endpoint
for the trigger dryrun using p o s t operation typically these are written to a http.Request
*/
type TriggerDryrunUsingPOSTParams struct {

	/*VidmDirRequestDTO
	  vidmDirRequestDTO

	*/
	VidmDirRequestDTO *models.VidmDirRequestDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) WithTimeout(timeout time.Duration) *TriggerDryrunUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) WithContext(ctx context.Context) *TriggerDryrunUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) WithHTTPClient(client *http.Client) *TriggerDryrunUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVidmDirRequestDTO adds the vidmDirRequestDTO to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) WithVidmDirRequestDTO(vidmDirRequestDTO *models.VidmDirRequestDTO) *TriggerDryrunUsingPOSTParams {
	o.SetVidmDirRequestDTO(vidmDirRequestDTO)
	return o
}

// SetVidmDirRequestDTO adds the vidmDirRequestDTO to the trigger dryrun using p o s t params
func (o *TriggerDryrunUsingPOSTParams) SetVidmDirRequestDTO(vidmDirRequestDTO *models.VidmDirRequestDTO) {
	o.VidmDirRequestDTO = vidmDirRequestDTO
}

// WriteToRequest writes these params to a swagger request
func (o *TriggerDryrunUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.VidmDirRequestDTO != nil {
		if err := r.SetBodyParam(o.VidmDirRequestDTO); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
