// Code generated by go-swagger; DO NOT EDIT.

package directory_management_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateADUserAttrMappingUsingPOSTReader is a Reader for the UpdateADUserAttrMappingUsingPOST structure.
type UpdateADUserAttrMappingUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateADUserAttrMappingUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateADUserAttrMappingUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewUpdateADUserAttrMappingUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateADUserAttrMappingUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateADUserAttrMappingUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateADUserAttrMappingUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateADUserAttrMappingUsingPOSTOK creates a UpdateADUserAttrMappingUsingPOSTOK with default headers values
func NewUpdateADUserAttrMappingUsingPOSTOK() *UpdateADUserAttrMappingUsingPOSTOK {
	return &UpdateADUserAttrMappingUsingPOSTOK{}
}

/*UpdateADUserAttrMappingUsingPOSTOK handles this case with default header values.

OK
*/
type UpdateADUserAttrMappingUsingPOSTOK struct {
	Payload interface{}
}

func (o *UpdateADUserAttrMappingUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/userattrmappings][%d] updateADUserAttrMappingUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *UpdateADUserAttrMappingUsingPOSTOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateADUserAttrMappingUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateADUserAttrMappingUsingPOSTCreated creates a UpdateADUserAttrMappingUsingPOSTCreated with default headers values
func NewUpdateADUserAttrMappingUsingPOSTCreated() *UpdateADUserAttrMappingUsingPOSTCreated {
	return &UpdateADUserAttrMappingUsingPOSTCreated{}
}

/*UpdateADUserAttrMappingUsingPOSTCreated handles this case with default header values.

Created
*/
type UpdateADUserAttrMappingUsingPOSTCreated struct {
}

func (o *UpdateADUserAttrMappingUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/userattrmappings][%d] updateADUserAttrMappingUsingPOSTCreated ", 201)
}

func (o *UpdateADUserAttrMappingUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateADUserAttrMappingUsingPOSTUnauthorized creates a UpdateADUserAttrMappingUsingPOSTUnauthorized with default headers values
func NewUpdateADUserAttrMappingUsingPOSTUnauthorized() *UpdateADUserAttrMappingUsingPOSTUnauthorized {
	return &UpdateADUserAttrMappingUsingPOSTUnauthorized{}
}

/*UpdateADUserAttrMappingUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateADUserAttrMappingUsingPOSTUnauthorized struct {
}

func (o *UpdateADUserAttrMappingUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/userattrmappings][%d] updateADUserAttrMappingUsingPOSTUnauthorized ", 401)
}

func (o *UpdateADUserAttrMappingUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateADUserAttrMappingUsingPOSTForbidden creates a UpdateADUserAttrMappingUsingPOSTForbidden with default headers values
func NewUpdateADUserAttrMappingUsingPOSTForbidden() *UpdateADUserAttrMappingUsingPOSTForbidden {
	return &UpdateADUserAttrMappingUsingPOSTForbidden{}
}

/*UpdateADUserAttrMappingUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type UpdateADUserAttrMappingUsingPOSTForbidden struct {
}

func (o *UpdateADUserAttrMappingUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/userattrmappings][%d] updateADUserAttrMappingUsingPOSTForbidden ", 403)
}

func (o *UpdateADUserAttrMappingUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateADUserAttrMappingUsingPOSTNotFound creates a UpdateADUserAttrMappingUsingPOSTNotFound with default headers values
func NewUpdateADUserAttrMappingUsingPOSTNotFound() *UpdateADUserAttrMappingUsingPOSTNotFound {
	return &UpdateADUserAttrMappingUsingPOSTNotFound{}
}

/*UpdateADUserAttrMappingUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type UpdateADUserAttrMappingUsingPOSTNotFound struct {
}

func (o *UpdateADUserAttrMappingUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/authzn/api/idp/dirConfigs/userattrmappings][%d] updateADUserAttrMappingUsingPOSTNotFound ", 404)
}

func (o *UpdateADUserAttrMappingUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
