// Code generated by go-swagger; DO NOT EDIT.

package file_browse_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// ExportNodeUsingPOSTReader is a Reader for the ExportNodeUsingPOST structure.
type ExportNodeUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportNodeUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExportNodeUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewExportNodeUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewExportNodeUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewExportNodeUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExportNodeUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExportNodeUsingPOSTOK creates a ExportNodeUsingPOSTOK with default headers values
func NewExportNodeUsingPOSTOK() *ExportNodeUsingPOSTOK {
	return &ExportNodeUsingPOSTOK{}
}

/*ExportNodeUsingPOSTOK handles this case with default header values.

OK
*/
type ExportNodeUsingPOSTOK struct {
	Payload []*models.NodeDTO
}

func (o *ExportNodeUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/crepo/api/content/nodes/export][%d] exportNodeUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *ExportNodeUsingPOSTOK) GetPayload() []*models.NodeDTO {
	return o.Payload
}

func (o *ExportNodeUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportNodeUsingPOSTCreated creates a ExportNodeUsingPOSTCreated with default headers values
func NewExportNodeUsingPOSTCreated() *ExportNodeUsingPOSTCreated {
	return &ExportNodeUsingPOSTCreated{}
}

/*ExportNodeUsingPOSTCreated handles this case with default header values.

Created
*/
type ExportNodeUsingPOSTCreated struct {
}

func (o *ExportNodeUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/crepo/api/content/nodes/export][%d] exportNodeUsingPOSTCreated ", 201)
}

func (o *ExportNodeUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportNodeUsingPOSTUnauthorized creates a ExportNodeUsingPOSTUnauthorized with default headers values
func NewExportNodeUsingPOSTUnauthorized() *ExportNodeUsingPOSTUnauthorized {
	return &ExportNodeUsingPOSTUnauthorized{}
}

/*ExportNodeUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type ExportNodeUsingPOSTUnauthorized struct {
}

func (o *ExportNodeUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/crepo/api/content/nodes/export][%d] exportNodeUsingPOSTUnauthorized ", 401)
}

func (o *ExportNodeUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportNodeUsingPOSTForbidden creates a ExportNodeUsingPOSTForbidden with default headers values
func NewExportNodeUsingPOSTForbidden() *ExportNodeUsingPOSTForbidden {
	return &ExportNodeUsingPOSTForbidden{}
}

/*ExportNodeUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type ExportNodeUsingPOSTForbidden struct {
}

func (o *ExportNodeUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/crepo/api/content/nodes/export][%d] exportNodeUsingPOSTForbidden ", 403)
}

func (o *ExportNodeUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportNodeUsingPOSTNotFound creates a ExportNodeUsingPOSTNotFound with default headers values
func NewExportNodeUsingPOSTNotFound() *ExportNodeUsingPOSTNotFound {
	return &ExportNodeUsingPOSTNotFound{}
}

/*ExportNodeUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type ExportNodeUsingPOSTNotFound struct {
}

func (o *ExportNodeUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/crepo/api/content/nodes/export][%d] exportNodeUsingPOSTNotFound ", 404)
}

func (o *ExportNodeUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
