// Code generated by go-swagger; DO NOT EDIT.

package environment_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCrossProductMonitervRAWithvROPSUsingPOSTParams creates a new CrossProductMonitervRAWithvROPSUsingPOSTParams object
// with the default values initialized.
func NewCrossProductMonitervRAWithvROPSUsingPOSTParams() *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	var ()
	return &CrossProductMonitervRAWithvROPSUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCrossProductMonitervRAWithvROPSUsingPOSTParamsWithTimeout creates a new CrossProductMonitervRAWithvROPSUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCrossProductMonitervRAWithvROPSUsingPOSTParamsWithTimeout(timeout time.Duration) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	var ()
	return &CrossProductMonitervRAWithvROPSUsingPOSTParams{

		timeout: timeout,
	}
}

// NewCrossProductMonitervRAWithvROPSUsingPOSTParamsWithContext creates a new CrossProductMonitervRAWithvROPSUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewCrossProductMonitervRAWithvROPSUsingPOSTParamsWithContext(ctx context.Context) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	var ()
	return &CrossProductMonitervRAWithvROPSUsingPOSTParams{

		Context: ctx,
	}
}

// NewCrossProductMonitervRAWithvROPSUsingPOSTParamsWithHTTPClient creates a new CrossProductMonitervRAWithvROPSUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCrossProductMonitervRAWithvROPSUsingPOSTParamsWithHTTPClient(client *http.Client) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	var ()
	return &CrossProductMonitervRAWithvROPSUsingPOSTParams{
		HTTPClient: client,
	}
}

/*CrossProductMonitervRAWithvROPSUsingPOSTParams contains all the parameters to send to the API endpoint
for the cross product moniterv r a withv r o p s using p o s t operation typically these are written to a http.Request
*/
type CrossProductMonitervRAWithvROPSUsingPOSTParams struct {

	/*EnvironmentID
	  environmentId

	*/
	EnvironmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) WithTimeout(timeout time.Duration) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) WithContext(ctx context.Context) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) WithHTTPClient(client *http.Client) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) WithEnvironmentID(environmentID string) *CrossProductMonitervRAWithvROPSUsingPOSTParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the cross product moniterv r a withv r o p s using p o s t params
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WriteToRequest writes these params to a swagger request
func (o *CrossProductMonitervRAWithvROPSUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentId
	if err := r.SetPathParam("environmentId", o.EnvironmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
