// Code generated by go-swagger; DO NOT EDIT.

package environment_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadEnviornmentLogsUsingPOSTParams creates a new DownloadEnviornmentLogsUsingPOSTParams object
// with the default values initialized.
func NewDownloadEnviornmentLogsUsingPOSTParams() *DownloadEnviornmentLogsUsingPOSTParams {
	var ()
	return &DownloadEnviornmentLogsUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadEnviornmentLogsUsingPOSTParamsWithTimeout creates a new DownloadEnviornmentLogsUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDownloadEnviornmentLogsUsingPOSTParamsWithTimeout(timeout time.Duration) *DownloadEnviornmentLogsUsingPOSTParams {
	var ()
	return &DownloadEnviornmentLogsUsingPOSTParams{

		timeout: timeout,
	}
}

// NewDownloadEnviornmentLogsUsingPOSTParamsWithContext creates a new DownloadEnviornmentLogsUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewDownloadEnviornmentLogsUsingPOSTParamsWithContext(ctx context.Context) *DownloadEnviornmentLogsUsingPOSTParams {
	var ()
	return &DownloadEnviornmentLogsUsingPOSTParams{

		Context: ctx,
	}
}

// NewDownloadEnviornmentLogsUsingPOSTParamsWithHTTPClient creates a new DownloadEnviornmentLogsUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDownloadEnviornmentLogsUsingPOSTParamsWithHTTPClient(client *http.Client) *DownloadEnviornmentLogsUsingPOSTParams {
	var ()
	return &DownloadEnviornmentLogsUsingPOSTParams{
		HTTPClient: client,
	}
}

/*DownloadEnviornmentLogsUsingPOSTParams contains all the parameters to send to the API endpoint
for the download enviornment logs using p o s t operation typically these are written to a http.Request
*/
type DownloadEnviornmentLogsUsingPOSTParams struct {

	/*EnvironmentID
	  environmentId

	*/
	EnvironmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) WithTimeout(timeout time.Duration) *DownloadEnviornmentLogsUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) WithContext(ctx context.Context) *DownloadEnviornmentLogsUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) WithHTTPClient(client *http.Client) *DownloadEnviornmentLogsUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) WithEnvironmentID(environmentID string) *DownloadEnviornmentLogsUsingPOSTParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the download enviornment logs using p o s t params
func (o *DownloadEnviornmentLogsUsingPOSTParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadEnviornmentLogsUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentId
	if err := r.SetPathParam("environmentId", o.EnvironmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
