// Code generated by go-swagger; DO NOT EDIT.

package environment_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEnvironmentDataFromIDUsingGETParams creates a new GetEnvironmentDataFromIDUsingGETParams object
// with the default values initialized.
func NewGetEnvironmentDataFromIDUsingGETParams() *GetEnvironmentDataFromIDUsingGETParams {
	var ()
	return &GetEnvironmentDataFromIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnvironmentDataFromIDUsingGETParamsWithTimeout creates a new GetEnvironmentDataFromIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEnvironmentDataFromIDUsingGETParamsWithTimeout(timeout time.Duration) *GetEnvironmentDataFromIDUsingGETParams {
	var ()
	return &GetEnvironmentDataFromIDUsingGETParams{

		timeout: timeout,
	}
}

// NewGetEnvironmentDataFromIDUsingGETParamsWithContext creates a new GetEnvironmentDataFromIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEnvironmentDataFromIDUsingGETParamsWithContext(ctx context.Context) *GetEnvironmentDataFromIDUsingGETParams {
	var ()
	return &GetEnvironmentDataFromIDUsingGETParams{

		Context: ctx,
	}
}

// NewGetEnvironmentDataFromIDUsingGETParamsWithHTTPClient creates a new GetEnvironmentDataFromIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEnvironmentDataFromIDUsingGETParamsWithHTTPClient(client *http.Client) *GetEnvironmentDataFromIDUsingGETParams {
	var ()
	return &GetEnvironmentDataFromIDUsingGETParams{
		HTTPClient: client,
	}
}

/*GetEnvironmentDataFromIDUsingGETParams contains all the parameters to send to the API endpoint
for the get environment data from Id using g e t operation typically these are written to a http.Request
*/
type GetEnvironmentDataFromIDUsingGETParams struct {

	/*EnvironmentID
	  environmentId

	*/
	EnvironmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) WithTimeout(timeout time.Duration) *GetEnvironmentDataFromIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) WithContext(ctx context.Context) *GetEnvironmentDataFromIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) WithHTTPClient(client *http.Client) *GetEnvironmentDataFromIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) WithEnvironmentID(environmentID string) *GetEnvironmentDataFromIDUsingGETParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the get environment data from Id using g e t params
func (o *GetEnvironmentDataFromIDUsingGETParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnvironmentDataFromIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentId
	if err := r.SetPathParam("environmentId", o.EnvironmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
