// Code generated by go-swagger; DO NOT EDIT.

package environment_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewValidateEnvironmentUsingPOST1Params creates a new ValidateEnvironmentUsingPOST1Params object
// with the default values initialized.
func NewValidateEnvironmentUsingPOST1Params() *ValidateEnvironmentUsingPOST1Params {
	var ()
	return &ValidateEnvironmentUsingPOST1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateEnvironmentUsingPOST1ParamsWithTimeout creates a new ValidateEnvironmentUsingPOST1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateEnvironmentUsingPOST1ParamsWithTimeout(timeout time.Duration) *ValidateEnvironmentUsingPOST1Params {
	var ()
	return &ValidateEnvironmentUsingPOST1Params{

		timeout: timeout,
	}
}

// NewValidateEnvironmentUsingPOST1ParamsWithContext creates a new ValidateEnvironmentUsingPOST1Params object
// with the default values initialized, and the ability to set a context for a request
func NewValidateEnvironmentUsingPOST1ParamsWithContext(ctx context.Context) *ValidateEnvironmentUsingPOST1Params {
	var ()
	return &ValidateEnvironmentUsingPOST1Params{

		Context: ctx,
	}
}

// NewValidateEnvironmentUsingPOST1ParamsWithHTTPClient creates a new ValidateEnvironmentUsingPOST1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateEnvironmentUsingPOST1ParamsWithHTTPClient(client *http.Client) *ValidateEnvironmentUsingPOST1Params {
	var ()
	return &ValidateEnvironmentUsingPOST1Params{
		HTTPClient: client,
	}
}

/*ValidateEnvironmentUsingPOST1Params contains all the parameters to send to the API endpoint
for the validate environment using p o s t 1 operation typically these are written to a http.Request
*/
type ValidateEnvironmentUsingPOST1Params struct {

	/*CreateEnvironmentUIRequest
	  createEnvironmentUiRequest

	*/
	CreateEnvironmentUIRequest *models.CreateEnvironmentUIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) WithTimeout(timeout time.Duration) *ValidateEnvironmentUsingPOST1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) WithContext(ctx context.Context) *ValidateEnvironmentUsingPOST1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) WithHTTPClient(client *http.Client) *ValidateEnvironmentUsingPOST1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateEnvironmentUIRequest adds the createEnvironmentUIRequest to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) WithCreateEnvironmentUIRequest(createEnvironmentUIRequest *models.CreateEnvironmentUIRequest) *ValidateEnvironmentUsingPOST1Params {
	o.SetCreateEnvironmentUIRequest(createEnvironmentUIRequest)
	return o
}

// SetCreateEnvironmentUIRequest adds the createEnvironmentUiRequest to the validate environment using p o s t 1 params
func (o *ValidateEnvironmentUsingPOST1Params) SetCreateEnvironmentUIRequest(createEnvironmentUIRequest *models.CreateEnvironmentUIRequest) {
	o.CreateEnvironmentUIRequest = createEnvironmentUIRequest
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateEnvironmentUsingPOST1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateEnvironmentUIRequest != nil {
		if err := r.SetBodyParam(o.CreateEnvironmentUIRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
