// Code generated by go-swagger; DO NOT EDIT.

package environment_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// ValidateAndDeployWindowsUsingPOSTReader is a Reader for the ValidateAndDeployWindowsUsingPOST structure.
type ValidateAndDeployWindowsUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateAndDeployWindowsUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateAndDeployWindowsUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewValidateAndDeployWindowsUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewValidateAndDeployWindowsUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewValidateAndDeployWindowsUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewValidateAndDeployWindowsUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewValidateAndDeployWindowsUsingPOSTOK creates a ValidateAndDeployWindowsUsingPOSTOK with default headers values
func NewValidateAndDeployWindowsUsingPOSTOK() *ValidateAndDeployWindowsUsingPOSTOK {
	return &ValidateAndDeployWindowsUsingPOSTOK{}
}

/*ValidateAndDeployWindowsUsingPOSTOK handles this case with default header values.

OK
*/
type ValidateAndDeployWindowsUsingPOSTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *ValidateAndDeployWindowsUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/prevalidateandinstallwindows][%d] validateAndDeployWindowsUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *ValidateAndDeployWindowsUsingPOSTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *ValidateAndDeployWindowsUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateAndDeployWindowsUsingPOSTCreated creates a ValidateAndDeployWindowsUsingPOSTCreated with default headers values
func NewValidateAndDeployWindowsUsingPOSTCreated() *ValidateAndDeployWindowsUsingPOSTCreated {
	return &ValidateAndDeployWindowsUsingPOSTCreated{}
}

/*ValidateAndDeployWindowsUsingPOSTCreated handles this case with default header values.

Created
*/
type ValidateAndDeployWindowsUsingPOSTCreated struct {
}

func (o *ValidateAndDeployWindowsUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/prevalidateandinstallwindows][%d] validateAndDeployWindowsUsingPOSTCreated ", 201)
}

func (o *ValidateAndDeployWindowsUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateAndDeployWindowsUsingPOSTUnauthorized creates a ValidateAndDeployWindowsUsingPOSTUnauthorized with default headers values
func NewValidateAndDeployWindowsUsingPOSTUnauthorized() *ValidateAndDeployWindowsUsingPOSTUnauthorized {
	return &ValidateAndDeployWindowsUsingPOSTUnauthorized{}
}

/*ValidateAndDeployWindowsUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type ValidateAndDeployWindowsUsingPOSTUnauthorized struct {
}

func (o *ValidateAndDeployWindowsUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/prevalidateandinstallwindows][%d] validateAndDeployWindowsUsingPOSTUnauthorized ", 401)
}

func (o *ValidateAndDeployWindowsUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateAndDeployWindowsUsingPOSTForbidden creates a ValidateAndDeployWindowsUsingPOSTForbidden with default headers values
func NewValidateAndDeployWindowsUsingPOSTForbidden() *ValidateAndDeployWindowsUsingPOSTForbidden {
	return &ValidateAndDeployWindowsUsingPOSTForbidden{}
}

/*ValidateAndDeployWindowsUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type ValidateAndDeployWindowsUsingPOSTForbidden struct {
}

func (o *ValidateAndDeployWindowsUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/prevalidateandinstallwindows][%d] validateAndDeployWindowsUsingPOSTForbidden ", 403)
}

func (o *ValidateAndDeployWindowsUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateAndDeployWindowsUsingPOSTNotFound creates a ValidateAndDeployWindowsUsingPOSTNotFound with default headers values
func NewValidateAndDeployWindowsUsingPOSTNotFound() *ValidateAndDeployWindowsUsingPOSTNotFound {
	return &ValidateAndDeployWindowsUsingPOSTNotFound{}
}

/*ValidateAndDeployWindowsUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type ValidateAndDeployWindowsUsingPOSTNotFound struct {
}

func (o *ValidateAndDeployWindowsUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/prevalidateandinstallwindows][%d] validateAndDeployWindowsUsingPOSTNotFound ", 404)
}

func (o *ValidateAndDeployWindowsUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
