// Code generated by go-swagger; DO NOT EDIT.

package environment_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// ValidateEnvironmentUsingPOSTReader is a Reader for the ValidateEnvironmentUsingPOST structure.
type ValidateEnvironmentUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateEnvironmentUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateEnvironmentUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewValidateEnvironmentUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewValidateEnvironmentUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewValidateEnvironmentUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewValidateEnvironmentUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewValidateEnvironmentUsingPOSTOK creates a ValidateEnvironmentUsingPOSTOK with default headers values
func NewValidateEnvironmentUsingPOSTOK() *ValidateEnvironmentUsingPOSTOK {
	return &ValidateEnvironmentUsingPOSTOK{}
}

/*ValidateEnvironmentUsingPOSTOK handles this case with default header values.

OK
*/
type ValidateEnvironmentUsingPOSTOK struct {
	Payload []*models.ValidationElement
}

func (o *ValidateEnvironmentUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/import/prevalidate][%d] validateEnvironmentUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *ValidateEnvironmentUsingPOSTOK) GetPayload() []*models.ValidationElement {
	return o.Payload
}

func (o *ValidateEnvironmentUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateEnvironmentUsingPOSTCreated creates a ValidateEnvironmentUsingPOSTCreated with default headers values
func NewValidateEnvironmentUsingPOSTCreated() *ValidateEnvironmentUsingPOSTCreated {
	return &ValidateEnvironmentUsingPOSTCreated{}
}

/*ValidateEnvironmentUsingPOSTCreated handles this case with default header values.

Created
*/
type ValidateEnvironmentUsingPOSTCreated struct {
}

func (o *ValidateEnvironmentUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/import/prevalidate][%d] validateEnvironmentUsingPOSTCreated ", 201)
}

func (o *ValidateEnvironmentUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateEnvironmentUsingPOSTUnauthorized creates a ValidateEnvironmentUsingPOSTUnauthorized with default headers values
func NewValidateEnvironmentUsingPOSTUnauthorized() *ValidateEnvironmentUsingPOSTUnauthorized {
	return &ValidateEnvironmentUsingPOSTUnauthorized{}
}

/*ValidateEnvironmentUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type ValidateEnvironmentUsingPOSTUnauthorized struct {
}

func (o *ValidateEnvironmentUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/import/prevalidate][%d] validateEnvironmentUsingPOSTUnauthorized ", 401)
}

func (o *ValidateEnvironmentUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateEnvironmentUsingPOSTForbidden creates a ValidateEnvironmentUsingPOSTForbidden with default headers values
func NewValidateEnvironmentUsingPOSTForbidden() *ValidateEnvironmentUsingPOSTForbidden {
	return &ValidateEnvironmentUsingPOSTForbidden{}
}

/*ValidateEnvironmentUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type ValidateEnvironmentUsingPOSTForbidden struct {
}

func (o *ValidateEnvironmentUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/import/prevalidate][%d] validateEnvironmentUsingPOSTForbidden ", 403)
}

func (o *ValidateEnvironmentUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateEnvironmentUsingPOSTNotFound creates a ValidateEnvironmentUsingPOSTNotFound with default headers values
func NewValidateEnvironmentUsingPOSTNotFound() *ValidateEnvironmentUsingPOSTNotFound {
	return &ValidateEnvironmentUsingPOSTNotFound{}
}

/*ValidateEnvironmentUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type ValidateEnvironmentUsingPOSTNotFound struct {
}

func (o *ValidateEnvironmentUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/import/prevalidate][%d] validateEnvironmentUsingPOSTNotFound ", 404)
}

func (o *ValidateEnvironmentUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
