// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ADIdentityGroupInfoDTO ADIdentityGroupInfoDTO
//
// swagger:model ADIdentityGroupInfoDTO
type ADIdentityGroupInfoDTO struct {

	// mapped group data
	MappedGroupData []*MappedGroupDataDTO `json:"mappedGroupData"`

	// num selected
	NumSelected int32 `json:"numSelected,omitempty"`

	// num total
	NumTotal int32 `json:"numTotal,omitempty"`

	// selected
	Selected bool `json:"selected,omitempty"`
}

// Validate validates this a d identity group info d t o
func (m *ADIdentityGroupInfoDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMappedGroupData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ADIdentityGroupInfoDTO) validateMappedGroupData(formats strfmt.Registry) error {

	if swag.IsZero(m.MappedGroupData) { // not required
		return nil
	}

	for i := 0; i < len(m.MappedGroupData); i++ {
		if swag.IsZero(m.MappedGroupData[i]) { // not required
			continue
		}

		if m.MappedGroupData[i] != nil {
			if err := m.MappedGroupData[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mappedGroupData" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ADIdentityGroupInfoDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ADIdentityGroupInfoDTO) UnmarshalBinary(b []byte) error {
	var res ADIdentityGroupInfoDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
