// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterVIP ClusterVIP
//
// swagger:model ClusterVIP
type ClusterVIP struct {

	// cluster vips
	ClusterVips []*ClusterVIPData `json:"clusterVips"`
}

// Validate validates this cluster v IP
func (m *ClusterVIP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterVips(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterVIP) validateClusterVips(formats strfmt.Registry) error {

	if swag.IsZero(m.ClusterVips) { // not required
		return nil
	}

	for i := 0; i < len(m.ClusterVips); i++ {
		if swag.IsZero(m.ClusterVips[i]) { // not required
			continue
		}

		if m.ClusterVips[i] != nil {
			if err := m.ClusterVips[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clusterVips" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterVIP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterVIP) UnmarshalBinary(b []byte) error {
	var res ClusterVIP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
