// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigParamsDTO ConfigParamsDTO
//
// swagger:model ConfigParamsDTO
type ConfigParamsDTO struct {

	// configname
	Configname string `json:"configname,omitempty"`

	// configvalue
	Configvalue string `json:"configvalue,omitempty"`
}

// Validate validates this config params d t o
func (m *ConfigParamsDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigParamsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigParamsDTO) UnmarshalBinary(b []byte) error {
	var res ConfigParamsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
