// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorCause ErrorCause
//
// swagger:model ErrorCause
type ErrorCause struct {

	// event Id
	EventID string `json:"eventId,omitempty"`

	// exception message
	ExceptionMessage string `json:"exceptionMessage,omitempty"`

	// exception stack trace
	ExceptionStackTrace string `json:"exceptionStackTrace,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// message Id
	MessageID string `json:"messageId,omitempty"`

	// properties
	Properties map[string]string `json:"properties,omitempty"`

	// retry
	Retry bool `json:"retry,omitempty"`
}

// Validate validates this error cause
func (m *ErrorCause) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorCause) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorCause) UnmarshalBinary(b []byte) error {
	var res ErrorCause
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
