// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LicenseValidateRequestDTO LicenseValidateRequestDTO
//
// swagger:model LicenseValidateRequestDTO
type LicenseValidateRequestDTO struct {

	// alias
	Alias string `json:"alias,omitempty"`

	// serial key
	SerialKey string `json:"serialKey,omitempty"`

	// transaction Id
	TransactionID string `json:"transactionId,omitempty"`

	// vmid
	Vmid string `json:"vmid,omitempty"`
}

// Validate validates this license validate request d t o
func (m *LicenseValidateRequestDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicenseValidateRequestDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseValidateRequestDTO) UnmarshalBinary(b []byte) error {
	var res LicenseValidateRequestDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
