// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NotificationDTOResponseBody NotificationDTOResponseBody
//
// swagger:model NotificationDTOResponseBody
type NotificationDTOResponseBody struct {

	// default unread truncate size
	DefaultUnreadTruncateSize int32 `json:"defaultUnreadTruncateSize,omitempty"`

	// notification d t os
	NotificationDTOs []*NotificationDTO `json:"notificationDTOs"`
}

// Validate validates this notification d t o response body
func (m *NotificationDTOResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNotificationDTOs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NotificationDTOResponseBody) validateNotificationDTOs(formats strfmt.Registry) error {

	if swag.IsZero(m.NotificationDTOs) { // not required
		return nil
	}

	for i := 0; i < len(m.NotificationDTOs); i++ {
		if swag.IsZero(m.NotificationDTOs[i]) { // not required
			continue
		}

		if m.NotificationDTOs[i] != nil {
			if err := m.NotificationDTOs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notificationDTOs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NotificationDTOResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationDTOResponseBody) UnmarshalBinary(b []byte) error {
	var res NotificationDTOResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
