// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductVersion ProductVersion
//
// swagger:model ProductVersion
type ProductVersion struct {

	// deployment type
	DeploymentType []string `json:"deploymentType"`

	// product deployment meta data
	ProductDeploymentMetaData *ProductDeploymentMetaData `json:"productDeploymentMetaData,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this product version
func (m *ProductVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProductDeploymentMetaData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductVersion) validateProductDeploymentMetaData(formats strfmt.Registry) error {

	if swag.IsZero(m.ProductDeploymentMetaData) { // not required
		return nil
	}

	if m.ProductDeploymentMetaData != nil {
		if err := m.ProductDeploymentMetaData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("productDeploymentMetaData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductVersion) UnmarshalBinary(b []byte) error {
	var res ProductVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
