// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductUpdateLBConfigDTO ProductUpdateLBConfigDTO
//
// swagger:model ProductUpdateLBConfigDTO
type ProductUpdateLBConfigDTO struct {

	// environment Id
	EnvironmentID string `json:"environmentId,omitempty"`

	// lb ssl terminated
	LbSslTerminated bool `json:"lbSslTerminated,omitempty"`

	// product Id
	ProductID string `json:"productId,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this product update l b config d t o
func (m *ProductUpdateLBConfigDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductUpdateLBConfigDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductUpdateLBConfigDTO) UnmarshalBinary(b []byte) error {
	var res ProductUpdateLBConfigDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
