// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetrustProductMetaDTO RetrustProductMetaDTO
//
// swagger:model RetrustProductMetaDTO
type RetrustProductMetaDTO struct {

	// retrust vidm cert prod list
	RetrustVidmCertProdList []*ProductReferenceEntryDTO `json:"retrustVidmCertProdList"`
}

// Validate validates this retrust product meta d t o
func (m *RetrustProductMetaDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRetrustVidmCertProdList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RetrustProductMetaDTO) validateRetrustVidmCertProdList(formats strfmt.Registry) error {

	if swag.IsZero(m.RetrustVidmCertProdList) { // not required
		return nil
	}

	for i := 0; i < len(m.RetrustVidmCertProdList); i++ {
		if swag.IsZero(m.RetrustVidmCertProdList[i]) { // not required
			continue
		}

		if m.RetrustVidmCertProdList[i] != nil {
			if err := m.RetrustVidmCertProdList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("retrustVidmCertProdList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RetrustProductMetaDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetrustProductMetaDTO) UnmarshalBinary(b []byte) error {
	var res RetrustProductMetaDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
