// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserMetadataDTO UserMetadataDTO
//
// swagger:model UserMetadataDTO
type UserMetadataDTO struct {

	// additional meta
	AdditionalMeta []string `json:"additionalMeta"`

	// distinguished name
	DistinguishedName string `json:"distinguishedName,omitempty"`

	// emails
	Emails []string `json:"emails"`

	// external Id
	ExternalID string `json:"externalId,omitempty"`

	// family name
	FamilyName string `json:"familyName,omitempty"`

	// given name
	GivenName string `json:"givenName,omitempty"`
}

// Validate validates this user metadata d t o
func (m *UserMetadataDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserMetadataDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserMetadataDTO) UnmarshalBinary(b []byte) error {
	var res UserMetadataDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
