// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VidmEnableMultitenancyRequestDTO VidmEnableMultitenancyRequestDTO
//
// swagger:model VidmEnableMultitenancyRequestDTO
type VidmEnableMultitenancyRequestDTO struct {

	// alias
	Alias string `json:"alias,omitempty"`

	// base tenant hostname
	BaseTenantHostname string `json:"baseTenantHostname,omitempty"`

	// configure tenant by path
	ConfigureTenantByPath bool `json:"configureTenantByPath,omitempty"`

	// is tenant configured by path
	IsTenantConfiguredByPath bool `json:"isTenantConfiguredByPath,omitempty"`

	// re register prod list
	ReRegisterProdList []*ProdInventoryMeta `json:"reRegisterProdList"`

	// request Id
	RequestID string `json:"requestId,omitempty"`

	// use service client
	UseServiceClient bool `json:"useServiceClient,omitempty"`

	// vidm admin password
	VidmAdminPassword string `json:"vidmAdminPassword,omitempty"`

	// vidm admin user
	VidmAdminUser string `json:"vidmAdminUser,omitempty"`

	// vidm domain name
	VidmDomainName string `json:"vidmDomainName,omitempty"`

	// vidm host
	VidmHost string `json:"vidmHost,omitempty"`

	// vidm o auth service client Id
	VidmOAuthServiceClientID string `json:"vidmOAuthServiceClientId,omitempty"`

	// vidm o auth service client secret
	VidmOAuthServiceClientSecret string `json:"vidmOAuthServiceClientSecret,omitempty"`

	// vidm root password
	VidmRootPassword string `json:"vidmRootPassword,omitempty"`

	// vidm Ssh password
	VidmSSHPassword string `json:"vidmSshPassword,omitempty"`

	// vidm tenant
	VidmTenant string `json:"vidmTenant,omitempty"`
}

// Validate validates this vidm enable multitenancy request d t o
func (m *VidmEnableMultitenancyRequestDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReRegisterProdList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VidmEnableMultitenancyRequestDTO) validateReRegisterProdList(formats strfmt.Registry) error {

	if swag.IsZero(m.ReRegisterProdList) { // not required
		return nil
	}

	for i := 0; i < len(m.ReRegisterProdList); i++ {
		if swag.IsZero(m.ReRegisterProdList[i]) { // not required
			continue
		}

		if m.ReRegisterProdList[i] != nil {
			if err := m.ReRegisterProdList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reRegisterProdList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *VidmEnableMultitenancyRequestDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VidmEnableMultitenancyRequestDTO) UnmarshalBinary(b []byte) error {
	var res VidmEnableMultitenancyRequestDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
