// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VidmHostBaseExDTO VidmHostBaseExDTO
//
// swagger:model VidmHostBaseExDTO
type VidmHostBaseExDTO struct {

	// base tenant hostname
	BaseTenantHostname string `json:"baseTenantHostname,omitempty"`

	// is tenant configured by path
	IsTenantConfiguredByPath bool `json:"isTenantConfiguredByPath,omitempty"`

	// request Id
	RequestID string `json:"requestId,omitempty"`

	// use service client
	UseServiceClient bool `json:"useServiceClient,omitempty"`

	// vidm admin password
	VidmAdminPassword string `json:"vidmAdminPassword,omitempty"`

	// vidm admin user
	VidmAdminUser string `json:"vidmAdminUser,omitempty"`

	// vidm domain name
	VidmDomainName string `json:"vidmDomainName,omitempty"`

	// vidm host
	VidmHost string `json:"vidmHost,omitempty"`

	// vidm o auth service client Id
	VidmOAuthServiceClientID string `json:"vidmOAuthServiceClientId,omitempty"`

	// vidm o auth service client secret
	VidmOAuthServiceClientSecret string `json:"vidmOAuthServiceClientSecret,omitempty"`

	// vidm tenant
	VidmTenant string `json:"vidmTenant,omitempty"`
}

// Validate validates this vidm host base ex d t o
func (m *VidmHostBaseExDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VidmHostBaseExDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VidmHostBaseExDTO) UnmarshalBinary(b []byte) error {
	var res VidmHostBaseExDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
