// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ViewPasswordRequestDTO ViewPasswordRequestDTO
//
// swagger:model ViewPasswordRequestDTO
type ViewPasswordRequestDTO struct {

	// root password
	RootPassword string `json:"rootPassword,omitempty"`
}

// Validate validates this view password request d t o
func (m *ViewPasswordRequestDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ViewPasswordRequestDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViewPasswordRequestDTO) UnmarshalBinary(b []byte) error {
	var res ViewPasswordRequestDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
