// Code generated by go-swagger; DO NOT EDIT.

package engine_interface_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteJobUsingGETParams creates a new DeleteJobUsingGETParams object
// with the default values initialized.
func NewDeleteJobUsingGETParams() *DeleteJobUsingGETParams {
	var ()
	return &DeleteJobUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteJobUsingGETParamsWithTimeout creates a new DeleteJobUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteJobUsingGETParamsWithTimeout(timeout time.Duration) *DeleteJobUsingGETParams {
	var ()
	return &DeleteJobUsingGETParams{

		timeout: timeout,
	}
}

// NewDeleteJobUsingGETParamsWithContext creates a new DeleteJobUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteJobUsingGETParamsWithContext(ctx context.Context) *DeleteJobUsingGETParams {
	var ()
	return &DeleteJobUsingGETParams{

		Context: ctx,
	}
}

// NewDeleteJobUsingGETParamsWithHTTPClient creates a new DeleteJobUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteJobUsingGETParamsWithHTTPClient(client *http.Client) *DeleteJobUsingGETParams {
	var ()
	return &DeleteJobUsingGETParams{
		HTTPClient: client,
	}
}

/*DeleteJobUsingGETParams contains all the parameters to send to the API endpoint
for the delete job using g e t operation typically these are written to a http.Request
*/
type DeleteJobUsingGETParams struct {

	/*Vmid
	  vmid

	*/
	Vmid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete job using g e t params
func (o *DeleteJobUsingGETParams) WithTimeout(timeout time.Duration) *DeleteJobUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete job using g e t params
func (o *DeleteJobUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete job using g e t params
func (o *DeleteJobUsingGETParams) WithContext(ctx context.Context) *DeleteJobUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete job using g e t params
func (o *DeleteJobUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete job using g e t params
func (o *DeleteJobUsingGETParams) WithHTTPClient(client *http.Client) *DeleteJobUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete job using g e t params
func (o *DeleteJobUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVmid adds the vmid to the delete job using g e t params
func (o *DeleteJobUsingGETParams) WithVmid(vmid string) *DeleteJobUsingGETParams {
	o.SetVmid(vmid)
	return o
}

// SetVmid adds the vmid to the delete job using g e t params
func (o *DeleteJobUsingGETParams) SetVmid(vmid string) {
	o.Vmid = vmid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteJobUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmid
	if err := r.SetPathParam("vmid", o.Vmid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
