// Code generated by go-swagger; DO NOT EDIT.

package engine_interface_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// GetJobStatusUsingGETReader is a Reader for the GetJobStatusUsingGET structure.
type GetJobStatusUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobStatusUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobStatusUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetJobStatusUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetJobStatusUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetJobStatusUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetJobStatusUsingGETOK creates a GetJobStatusUsingGETOK with default headers values
func NewGetJobStatusUsingGETOK() *GetJobStatusUsingGETOK {
	return &GetJobStatusUsingGETOK{}
}

/*GetJobStatusUsingGETOK handles this case with default header values.

OK
*/
type GetJobStatusUsingGETOK struct {
	Payload *models.UserRequestProgress
}

func (o *GetJobStatusUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /lcm/automata/api/engine/job/status/{vmid}][%d] getJobStatusUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetJobStatusUsingGETOK) GetPayload() *models.UserRequestProgress {
	return o.Payload
}

func (o *GetJobStatusUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserRequestProgress)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobStatusUsingGETUnauthorized creates a GetJobStatusUsingGETUnauthorized with default headers values
func NewGetJobStatusUsingGETUnauthorized() *GetJobStatusUsingGETUnauthorized {
	return &GetJobStatusUsingGETUnauthorized{}
}

/*GetJobStatusUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetJobStatusUsingGETUnauthorized struct {
}

func (o *GetJobStatusUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /lcm/automata/api/engine/job/status/{vmid}][%d] getJobStatusUsingGETUnauthorized ", 401)
}

func (o *GetJobStatusUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetJobStatusUsingGETForbidden creates a GetJobStatusUsingGETForbidden with default headers values
func NewGetJobStatusUsingGETForbidden() *GetJobStatusUsingGETForbidden {
	return &GetJobStatusUsingGETForbidden{}
}

/*GetJobStatusUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetJobStatusUsingGETForbidden struct {
}

func (o *GetJobStatusUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /lcm/automata/api/engine/job/status/{vmid}][%d] getJobStatusUsingGETForbidden ", 403)
}

func (o *GetJobStatusUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetJobStatusUsingGETNotFound creates a GetJobStatusUsingGETNotFound with default headers values
func NewGetJobStatusUsingGETNotFound() *GetJobStatusUsingGETNotFound {
	return &GetJobStatusUsingGETNotFound{}
}

/*GetJobStatusUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetJobStatusUsingGETNotFound struct {
}

func (o *GetJobStatusUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /lcm/automata/api/engine/job/status/{vmid}][%d] getJobStatusUsingGETNotFound ", 404)
}

func (o *GetJobStatusUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
