// Code generated by go-swagger; DO NOT EDIT.

package engine_interface_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetJobExecutionPathUsingGETParams creates a new GetJobExecutionPathUsingGETParams object
// with the default values initialized.
func NewGetJobExecutionPathUsingGETParams() *GetJobExecutionPathUsingGETParams {
	var ()
	return &GetJobExecutionPathUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetJobExecutionPathUsingGETParamsWithTimeout creates a new GetJobExecutionPathUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetJobExecutionPathUsingGETParamsWithTimeout(timeout time.Duration) *GetJobExecutionPathUsingGETParams {
	var ()
	return &GetJobExecutionPathUsingGETParams{

		timeout: timeout,
	}
}

// NewGetJobExecutionPathUsingGETParamsWithContext creates a new GetJobExecutionPathUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetJobExecutionPathUsingGETParamsWithContext(ctx context.Context) *GetJobExecutionPathUsingGETParams {
	var ()
	return &GetJobExecutionPathUsingGETParams{

		Context: ctx,
	}
}

// NewGetJobExecutionPathUsingGETParamsWithHTTPClient creates a new GetJobExecutionPathUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetJobExecutionPathUsingGETParamsWithHTTPClient(client *http.Client) *GetJobExecutionPathUsingGETParams {
	var ()
	return &GetJobExecutionPathUsingGETParams{
		HTTPClient: client,
	}
}

/*GetJobExecutionPathUsingGETParams contains all the parameters to send to the API endpoint
for the get job execution path using g e t operation typically these are written to a http.Request
*/
type GetJobExecutionPathUsingGETParams struct {

	/*Vmid
	  vmid

	*/
	Vmid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) WithTimeout(timeout time.Duration) *GetJobExecutionPathUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) WithContext(ctx context.Context) *GetJobExecutionPathUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) WithHTTPClient(client *http.Client) *GetJobExecutionPathUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVmid adds the vmid to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) WithVmid(vmid string) *GetJobExecutionPathUsingGETParams {
	o.SetVmid(vmid)
	return o
}

// SetVmid adds the vmid to the get job execution path using g e t params
func (o *GetJobExecutionPathUsingGETParams) SetVmid(vmid string) {
	o.Vmid = vmid
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobExecutionPathUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmid
	if err := r.SetPathParam("vmid", o.Vmid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
