// Code generated by go-swagger; DO NOT EDIT.

package data_center_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateZoneUsingPOSTReader is a Reader for the CreateZoneUsingPOST structure.
type CreateZoneUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateZoneUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateZoneUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewCreateZoneUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateZoneUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateZoneUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateZoneUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateZoneUsingPOSTOK creates a CreateZoneUsingPOSTOK with default headers values
func NewCreateZoneUsingPOSTOK() *CreateZoneUsingPOSTOK {
	return &CreateZoneUsingPOSTOK{}
}

/*CreateZoneUsingPOSTOK handles this case with default header values.

OK
*/
type CreateZoneUsingPOSTOK struct {
}

func (o *CreateZoneUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones][%d] createZoneUsingPOSTOK ", 200)
}

func (o *CreateZoneUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateZoneUsingPOSTCreated creates a CreateZoneUsingPOSTCreated with default headers values
func NewCreateZoneUsingPOSTCreated() *CreateZoneUsingPOSTCreated {
	return &CreateZoneUsingPOSTCreated{}
}

/*CreateZoneUsingPOSTCreated handles this case with default header values.

Created
*/
type CreateZoneUsingPOSTCreated struct {
}

func (o *CreateZoneUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones][%d] createZoneUsingPOSTCreated ", 201)
}

func (o *CreateZoneUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateZoneUsingPOSTUnauthorized creates a CreateZoneUsingPOSTUnauthorized with default headers values
func NewCreateZoneUsingPOSTUnauthorized() *CreateZoneUsingPOSTUnauthorized {
	return &CreateZoneUsingPOSTUnauthorized{}
}

/*CreateZoneUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateZoneUsingPOSTUnauthorized struct {
}

func (o *CreateZoneUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones][%d] createZoneUsingPOSTUnauthorized ", 401)
}

func (o *CreateZoneUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateZoneUsingPOSTForbidden creates a CreateZoneUsingPOSTForbidden with default headers values
func NewCreateZoneUsingPOSTForbidden() *CreateZoneUsingPOSTForbidden {
	return &CreateZoneUsingPOSTForbidden{}
}

/*CreateZoneUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type CreateZoneUsingPOSTForbidden struct {
}

func (o *CreateZoneUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones][%d] createZoneUsingPOSTForbidden ", 403)
}

func (o *CreateZoneUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateZoneUsingPOSTNotFound creates a CreateZoneUsingPOSTNotFound with default headers values
func NewCreateZoneUsingPOSTNotFound() *CreateZoneUsingPOSTNotFound {
	return &CreateZoneUsingPOSTNotFound{}
}

/*CreateZoneUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type CreateZoneUsingPOSTNotFound struct {
}

func (o *CreateZoneUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones][%d] createZoneUsingPOSTNotFound ", 404)
}

func (o *CreateZoneUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
