// Code generated by go-swagger; DO NOT EDIT.

package data_center_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDataCentersUsingDELETEReader is a Reader for the DeleteDataCentersUsingDELETE structure.
type DeleteDataCentersUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDataCentersUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDataCentersUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteDataCentersUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteDataCentersUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteDataCentersUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDataCentersUsingDELETEOK creates a DeleteDataCentersUsingDELETEOK with default headers values
func NewDeleteDataCentersUsingDELETEOK() *DeleteDataCentersUsingDELETEOK {
	return &DeleteDataCentersUsingDELETEOK{}
}

/*DeleteDataCentersUsingDELETEOK handles this case with default header values.

OK
*/
type DeleteDataCentersUsingDELETEOK struct {
}

func (o *DeleteDataCentersUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /lcm/lcops/api/datacenters/{dataCenterName}][%d] deleteDataCentersUsingDELETEOK ", 200)
}

func (o *DeleteDataCentersUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDataCentersUsingDELETENoContent creates a DeleteDataCentersUsingDELETENoContent with default headers values
func NewDeleteDataCentersUsingDELETENoContent() *DeleteDataCentersUsingDELETENoContent {
	return &DeleteDataCentersUsingDELETENoContent{}
}

/*DeleteDataCentersUsingDELETENoContent handles this case with default header values.

No Content
*/
type DeleteDataCentersUsingDELETENoContent struct {
}

func (o *DeleteDataCentersUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /lcm/lcops/api/datacenters/{dataCenterName}][%d] deleteDataCentersUsingDELETENoContent ", 204)
}

func (o *DeleteDataCentersUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDataCentersUsingDELETEUnauthorized creates a DeleteDataCentersUsingDELETEUnauthorized with default headers values
func NewDeleteDataCentersUsingDELETEUnauthorized() *DeleteDataCentersUsingDELETEUnauthorized {
	return &DeleteDataCentersUsingDELETEUnauthorized{}
}

/*DeleteDataCentersUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteDataCentersUsingDELETEUnauthorized struct {
}

func (o *DeleteDataCentersUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /lcm/lcops/api/datacenters/{dataCenterName}][%d] deleteDataCentersUsingDELETEUnauthorized ", 401)
}

func (o *DeleteDataCentersUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDataCentersUsingDELETEForbidden creates a DeleteDataCentersUsingDELETEForbidden with default headers values
func NewDeleteDataCentersUsingDELETEForbidden() *DeleteDataCentersUsingDELETEForbidden {
	return &DeleteDataCentersUsingDELETEForbidden{}
}

/*DeleteDataCentersUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type DeleteDataCentersUsingDELETEForbidden struct {
}

func (o *DeleteDataCentersUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /lcm/lcops/api/datacenters/{dataCenterName}][%d] deleteDataCentersUsingDELETEForbidden ", 403)
}

func (o *DeleteDataCentersUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
