// Code generated by go-swagger; DO NOT EDIT.

package data_center_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRegionUsingGETParams creates a new GetRegionUsingGETParams object
// with the default values initialized.
func NewGetRegionUsingGETParams() *GetRegionUsingGETParams {

	return &GetRegionUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegionUsingGETParamsWithTimeout creates a new GetRegionUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegionUsingGETParamsWithTimeout(timeout time.Duration) *GetRegionUsingGETParams {

	return &GetRegionUsingGETParams{

		timeout: timeout,
	}
}

// NewGetRegionUsingGETParamsWithContext creates a new GetRegionUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegionUsingGETParamsWithContext(ctx context.Context) *GetRegionUsingGETParams {

	return &GetRegionUsingGETParams{

		Context: ctx,
	}
}

// NewGetRegionUsingGETParamsWithHTTPClient creates a new GetRegionUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRegionUsingGETParamsWithHTTPClient(client *http.Client) *GetRegionUsingGETParams {

	return &GetRegionUsingGETParams{
		HTTPClient: client,
	}
}

/*GetRegionUsingGETParams contains all the parameters to send to the API endpoint
for the get region using g e t operation typically these are written to a http.Request
*/
type GetRegionUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get region using g e t params
func (o *GetRegionUsingGETParams) WithTimeout(timeout time.Duration) *GetRegionUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get region using g e t params
func (o *GetRegionUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get region using g e t params
func (o *GetRegionUsingGETParams) WithContext(ctx context.Context) *GetRegionUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get region using g e t params
func (o *GetRegionUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get region using g e t params
func (o *GetRegionUsingGETParams) WithHTTPClient(client *http.Client) *GetRegionUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get region using g e t params
func (o *GetRegionUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegionUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
