// Code generated by go-swagger; DO NOT EDIT.

package data_center_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// TriggerVCenterDataCollectionUsingPUTReader is a Reader for the TriggerVCenterDataCollectionUsingPUT structure.
type TriggerVCenterDataCollectionUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TriggerVCenterDataCollectionUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTriggerVCenterDataCollectionUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewTriggerVCenterDataCollectionUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewTriggerVCenterDataCollectionUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewTriggerVCenterDataCollectionUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTriggerVCenterDataCollectionUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTriggerVCenterDataCollectionUsingPUTOK creates a TriggerVCenterDataCollectionUsingPUTOK with default headers values
func NewTriggerVCenterDataCollectionUsingPUTOK() *TriggerVCenterDataCollectionUsingPUTOK {
	return &TriggerVCenterDataCollectionUsingPUTOK{}
}

/*TriggerVCenterDataCollectionUsingPUTOK handles this case with default header values.

OK
*/
type TriggerVCenterDataCollectionUsingPUTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *TriggerVCenterDataCollectionUsingPUTOK) Error() string {
	return fmt.Sprintf("[PUT /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones/{zoneName}/vCenters/{vCenterName}/datacollection][%d] triggerVCenterDataCollectionUsingPUTOK  %+v", 200, o.Payload)
}

func (o *TriggerVCenterDataCollectionUsingPUTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *TriggerVCenterDataCollectionUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriggerVCenterDataCollectionUsingPUTCreated creates a TriggerVCenterDataCollectionUsingPUTCreated with default headers values
func NewTriggerVCenterDataCollectionUsingPUTCreated() *TriggerVCenterDataCollectionUsingPUTCreated {
	return &TriggerVCenterDataCollectionUsingPUTCreated{}
}

/*TriggerVCenterDataCollectionUsingPUTCreated handles this case with default header values.

Created
*/
type TriggerVCenterDataCollectionUsingPUTCreated struct {
}

func (o *TriggerVCenterDataCollectionUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones/{zoneName}/vCenters/{vCenterName}/datacollection][%d] triggerVCenterDataCollectionUsingPUTCreated ", 201)
}

func (o *TriggerVCenterDataCollectionUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTriggerVCenterDataCollectionUsingPUTUnauthorized creates a TriggerVCenterDataCollectionUsingPUTUnauthorized with default headers values
func NewTriggerVCenterDataCollectionUsingPUTUnauthorized() *TriggerVCenterDataCollectionUsingPUTUnauthorized {
	return &TriggerVCenterDataCollectionUsingPUTUnauthorized{}
}

/*TriggerVCenterDataCollectionUsingPUTUnauthorized handles this case with default header values.

Unauthorized
*/
type TriggerVCenterDataCollectionUsingPUTUnauthorized struct {
}

func (o *TriggerVCenterDataCollectionUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones/{zoneName}/vCenters/{vCenterName}/datacollection][%d] triggerVCenterDataCollectionUsingPUTUnauthorized ", 401)
}

func (o *TriggerVCenterDataCollectionUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTriggerVCenterDataCollectionUsingPUTForbidden creates a TriggerVCenterDataCollectionUsingPUTForbidden with default headers values
func NewTriggerVCenterDataCollectionUsingPUTForbidden() *TriggerVCenterDataCollectionUsingPUTForbidden {
	return &TriggerVCenterDataCollectionUsingPUTForbidden{}
}

/*TriggerVCenterDataCollectionUsingPUTForbidden handles this case with default header values.

Forbidden
*/
type TriggerVCenterDataCollectionUsingPUTForbidden struct {
}

func (o *TriggerVCenterDataCollectionUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones/{zoneName}/vCenters/{vCenterName}/datacollection][%d] triggerVCenterDataCollectionUsingPUTForbidden ", 403)
}

func (o *TriggerVCenterDataCollectionUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTriggerVCenterDataCollectionUsingPUTNotFound creates a TriggerVCenterDataCollectionUsingPUTNotFound with default headers values
func NewTriggerVCenterDataCollectionUsingPUTNotFound() *TriggerVCenterDataCollectionUsingPUTNotFound {
	return &TriggerVCenterDataCollectionUsingPUTNotFound{}
}

/*TriggerVCenterDataCollectionUsingPUTNotFound handles this case with default header values.

Not Found
*/
type TriggerVCenterDataCollectionUsingPUTNotFound struct {
}

func (o *TriggerVCenterDataCollectionUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /lcm/lcops/api/datacenters/{dataCenterName}/regions/{regionName}/zones/{zoneName}/vCenters/{vCenterName}/datacollection][%d] triggerVCenterDataCollectionUsingPUTNotFound ", 404)
}

func (o *TriggerVCenterDataCollectionUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
