// Code generated by go-swagger; DO NOT EDIT.

package authentication_group_role_mapping_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewCreateGroupRoleMappingUsingPOSTParams creates a new CreateGroupRoleMappingUsingPOSTParams object
// with the default values initialized.
func NewCreateGroupRoleMappingUsingPOSTParams() *CreateGroupRoleMappingUsingPOSTParams {
	var ()
	return &CreateGroupRoleMappingUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGroupRoleMappingUsingPOSTParamsWithTimeout creates a new CreateGroupRoleMappingUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGroupRoleMappingUsingPOSTParamsWithTimeout(timeout time.Duration) *CreateGroupRoleMappingUsingPOSTParams {
	var ()
	return &CreateGroupRoleMappingUsingPOSTParams{

		timeout: timeout,
	}
}

// NewCreateGroupRoleMappingUsingPOSTParamsWithContext creates a new CreateGroupRoleMappingUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateGroupRoleMappingUsingPOSTParamsWithContext(ctx context.Context) *CreateGroupRoleMappingUsingPOSTParams {
	var ()
	return &CreateGroupRoleMappingUsingPOSTParams{

		Context: ctx,
	}
}

// NewCreateGroupRoleMappingUsingPOSTParamsWithHTTPClient creates a new CreateGroupRoleMappingUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateGroupRoleMappingUsingPOSTParamsWithHTTPClient(client *http.Client) *CreateGroupRoleMappingUsingPOSTParams {
	var ()
	return &CreateGroupRoleMappingUsingPOSTParams{
		HTTPClient: client,
	}
}

/*CreateGroupRoleMappingUsingPOSTParams contains all the parameters to send to the API endpoint
for the create group role mapping using p o s t operation typically these are written to a http.Request
*/
type CreateGroupRoleMappingUsingPOSTParams struct {

	/*GroupRoleMappingDTO
	  groupRoleMappingDTO

	*/
	GroupRoleMappingDTO *models.GroupRoleMappingDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) WithTimeout(timeout time.Duration) *CreateGroupRoleMappingUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) WithContext(ctx context.Context) *CreateGroupRoleMappingUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) WithHTTPClient(client *http.Client) *CreateGroupRoleMappingUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupRoleMappingDTO adds the groupRoleMappingDTO to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) WithGroupRoleMappingDTO(groupRoleMappingDTO *models.GroupRoleMappingDTO) *CreateGroupRoleMappingUsingPOSTParams {
	o.SetGroupRoleMappingDTO(groupRoleMappingDTO)
	return o
}

// SetGroupRoleMappingDTO adds the groupRoleMappingDTO to the create group role mapping using p o s t params
func (o *CreateGroupRoleMappingUsingPOSTParams) SetGroupRoleMappingDTO(groupRoleMappingDTO *models.GroupRoleMappingDTO) {
	o.GroupRoleMappingDTO = groupRoleMappingDTO
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGroupRoleMappingUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.GroupRoleMappingDTO != nil {
		if err := r.SetBodyParam(o.GroupRoleMappingDTO); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
