// Code generated by go-swagger; DO NOT EDIT.

package authentication_group_role_mapping_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAllGroupRoleMappingsUsingDELETEParams creates a new DeleteAllGroupRoleMappingsUsingDELETEParams object
// with the default values initialized.
func NewDeleteAllGroupRoleMappingsUsingDELETEParams() *DeleteAllGroupRoleMappingsUsingDELETEParams {

	return &DeleteAllGroupRoleMappingsUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAllGroupRoleMappingsUsingDELETEParamsWithTimeout creates a new DeleteAllGroupRoleMappingsUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAllGroupRoleMappingsUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteAllGroupRoleMappingsUsingDELETEParams {

	return &DeleteAllGroupRoleMappingsUsingDELETEParams{

		timeout: timeout,
	}
}

// NewDeleteAllGroupRoleMappingsUsingDELETEParamsWithContext creates a new DeleteAllGroupRoleMappingsUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAllGroupRoleMappingsUsingDELETEParamsWithContext(ctx context.Context) *DeleteAllGroupRoleMappingsUsingDELETEParams {

	return &DeleteAllGroupRoleMappingsUsingDELETEParams{

		Context: ctx,
	}
}

// NewDeleteAllGroupRoleMappingsUsingDELETEParamsWithHTTPClient creates a new DeleteAllGroupRoleMappingsUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAllGroupRoleMappingsUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteAllGroupRoleMappingsUsingDELETEParams {

	return &DeleteAllGroupRoleMappingsUsingDELETEParams{
		HTTPClient: client,
	}
}

/*DeleteAllGroupRoleMappingsUsingDELETEParams contains all the parameters to send to the API endpoint
for the delete all group role mappings using d e l e t e operation typically these are written to a http.Request
*/
type DeleteAllGroupRoleMappingsUsingDELETEParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete all group role mappings using d e l e t e params
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteAllGroupRoleMappingsUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete all group role mappings using d e l e t e params
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete all group role mappings using d e l e t e params
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) WithContext(ctx context.Context) *DeleteAllGroupRoleMappingsUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete all group role mappings using d e l e t e params
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete all group role mappings using d e l e t e params
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteAllGroupRoleMappingsUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete all group role mappings using d e l e t e params
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAllGroupRoleMappingsUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
