// Code generated by go-swagger; DO NOT EDIT.

package authentication_group_role_mapping_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGroupMappingGivenGroupIDUsingDELETEParams creates a new DeleteGroupMappingGivenGroupIDUsingDELETEParams object
// with the default values initialized.
func NewDeleteGroupMappingGivenGroupIDUsingDELETEParams() *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	var ()
	return &DeleteGroupMappingGivenGroupIDUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteGroupMappingGivenGroupIDUsingDELETEParamsWithTimeout creates a new DeleteGroupMappingGivenGroupIDUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteGroupMappingGivenGroupIDUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	var ()
	return &DeleteGroupMappingGivenGroupIDUsingDELETEParams{

		timeout: timeout,
	}
}

// NewDeleteGroupMappingGivenGroupIDUsingDELETEParamsWithContext creates a new DeleteGroupMappingGivenGroupIDUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteGroupMappingGivenGroupIDUsingDELETEParamsWithContext(ctx context.Context) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	var ()
	return &DeleteGroupMappingGivenGroupIDUsingDELETEParams{

		Context: ctx,
	}
}

// NewDeleteGroupMappingGivenGroupIDUsingDELETEParamsWithHTTPClient creates a new DeleteGroupMappingGivenGroupIDUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteGroupMappingGivenGroupIDUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	var ()
	return &DeleteGroupMappingGivenGroupIDUsingDELETEParams{
		HTTPClient: client,
	}
}

/*DeleteGroupMappingGivenGroupIDUsingDELETEParams contains all the parameters to send to the API endpoint
for the delete group mapping given group Id using d e l e t e operation typically these are written to a http.Request
*/
type DeleteGroupMappingGivenGroupIDUsingDELETEParams struct {

	/*Groupvmid
	  groupvmid

	*/
	Groupvmid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) WithContext(ctx context.Context) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupvmid adds the groupvmid to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) WithGroupvmid(groupvmid string) *DeleteGroupMappingGivenGroupIDUsingDELETEParams {
	o.SetGroupvmid(groupvmid)
	return o
}

// SetGroupvmid adds the groupvmid to the delete group mapping given group Id using d e l e t e params
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) SetGroupvmid(groupvmid string) {
	o.Groupvmid = groupvmid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteGroupMappingGivenGroupIDUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupvmid
	if err := r.SetPathParam("groupvmid", o.Groupvmid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
