// Code generated by go-swagger; DO NOT EDIT.

package authentication_group_role_mapping_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupRoleMappingGivenGroupIDUsingGETParams creates a new GetGroupRoleMappingGivenGroupIDUsingGETParams object
// with the default values initialized.
func NewGetGroupRoleMappingGivenGroupIDUsingGETParams() *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	var ()
	return &GetGroupRoleMappingGivenGroupIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupRoleMappingGivenGroupIDUsingGETParamsWithTimeout creates a new GetGroupRoleMappingGivenGroupIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGroupRoleMappingGivenGroupIDUsingGETParamsWithTimeout(timeout time.Duration) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	var ()
	return &GetGroupRoleMappingGivenGroupIDUsingGETParams{

		timeout: timeout,
	}
}

// NewGetGroupRoleMappingGivenGroupIDUsingGETParamsWithContext creates a new GetGroupRoleMappingGivenGroupIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGroupRoleMappingGivenGroupIDUsingGETParamsWithContext(ctx context.Context) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	var ()
	return &GetGroupRoleMappingGivenGroupIDUsingGETParams{

		Context: ctx,
	}
}

// NewGetGroupRoleMappingGivenGroupIDUsingGETParamsWithHTTPClient creates a new GetGroupRoleMappingGivenGroupIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGroupRoleMappingGivenGroupIDUsingGETParamsWithHTTPClient(client *http.Client) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	var ()
	return &GetGroupRoleMappingGivenGroupIDUsingGETParams{
		HTTPClient: client,
	}
}

/*GetGroupRoleMappingGivenGroupIDUsingGETParams contains all the parameters to send to the API endpoint
for the get group role mapping given group Id using g e t operation typically these are written to a http.Request
*/
type GetGroupRoleMappingGivenGroupIDUsingGETParams struct {

	/*Groupvmid
	  groupvmid

	*/
	Groupvmid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) WithTimeout(timeout time.Duration) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) WithContext(ctx context.Context) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) WithHTTPClient(client *http.Client) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupvmid adds the groupvmid to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) WithGroupvmid(groupvmid string) *GetGroupRoleMappingGivenGroupIDUsingGETParams {
	o.SetGroupvmid(groupvmid)
	return o
}

// SetGroupvmid adds the groupvmid to the get group role mapping given group Id using g e t params
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) SetGroupvmid(groupvmid string) {
	o.Groupvmid = groupvmid
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupRoleMappingGivenGroupIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupvmid
	if err := r.SetPathParam("groupvmid", o.Groupvmid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
