// Code generated by go-swagger; DO NOT EDIT.

package i_market_place_app_metadata_controller_impl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMarketPlaceAppByParentIDUsingGETParams creates a new GetMarketPlaceAppByParentIDUsingGETParams object
// with the default values initialized.
func NewGetMarketPlaceAppByParentIDUsingGETParams() *GetMarketPlaceAppByParentIDUsingGETParams {
	var ()
	return &GetMarketPlaceAppByParentIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMarketPlaceAppByParentIDUsingGETParamsWithTimeout creates a new GetMarketPlaceAppByParentIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMarketPlaceAppByParentIDUsingGETParamsWithTimeout(timeout time.Duration) *GetMarketPlaceAppByParentIDUsingGETParams {
	var ()
	return &GetMarketPlaceAppByParentIDUsingGETParams{

		timeout: timeout,
	}
}

// NewGetMarketPlaceAppByParentIDUsingGETParamsWithContext creates a new GetMarketPlaceAppByParentIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMarketPlaceAppByParentIDUsingGETParamsWithContext(ctx context.Context) *GetMarketPlaceAppByParentIDUsingGETParams {
	var ()
	return &GetMarketPlaceAppByParentIDUsingGETParams{

		Context: ctx,
	}
}

// NewGetMarketPlaceAppByParentIDUsingGETParamsWithHTTPClient creates a new GetMarketPlaceAppByParentIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMarketPlaceAppByParentIDUsingGETParamsWithHTTPClient(client *http.Client) *GetMarketPlaceAppByParentIDUsingGETParams {
	var ()
	return &GetMarketPlaceAppByParentIDUsingGETParams{
		HTTPClient: client,
	}
}

/*GetMarketPlaceAppByParentIDUsingGETParams contains all the parameters to send to the API endpoint
for the get market place app by parent Id using g e t operation typically these are written to a http.Request
*/
type GetMarketPlaceAppByParentIDUsingGETParams struct {

	/*ParentID
	  parentId

	*/
	ParentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) WithTimeout(timeout time.Duration) *GetMarketPlaceAppByParentIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) WithContext(ctx context.Context) *GetMarketPlaceAppByParentIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) WithHTTPClient(client *http.Client) *GetMarketPlaceAppByParentIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParentID adds the parentID to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) WithParentID(parentID string) *GetMarketPlaceAppByParentIDUsingGETParams {
	o.SetParentID(parentID)
	return o
}

// SetParentID adds the parentId to the get market place app by parent Id using g e t params
func (o *GetMarketPlaceAppByParentIDUsingGETParams) SetParentID(parentID string) {
	o.ParentID = parentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMarketPlaceAppByParentIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param parentId
	if err := r.SetPathParam("parentId", o.ParentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
