// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewApplyProductPatchUsingPOSTParams creates a new ApplyProductPatchUsingPOSTParams object
// with the default values initialized.
func NewApplyProductPatchUsingPOSTParams() *ApplyProductPatchUsingPOSTParams {
	var ()
	return &ApplyProductPatchUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewApplyProductPatchUsingPOSTParamsWithTimeout creates a new ApplyProductPatchUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewApplyProductPatchUsingPOSTParamsWithTimeout(timeout time.Duration) *ApplyProductPatchUsingPOSTParams {
	var ()
	return &ApplyProductPatchUsingPOSTParams{

		timeout: timeout,
	}
}

// NewApplyProductPatchUsingPOSTParamsWithContext creates a new ApplyProductPatchUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewApplyProductPatchUsingPOSTParamsWithContext(ctx context.Context) *ApplyProductPatchUsingPOSTParams {
	var ()
	return &ApplyProductPatchUsingPOSTParams{

		Context: ctx,
	}
}

// NewApplyProductPatchUsingPOSTParamsWithHTTPClient creates a new ApplyProductPatchUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewApplyProductPatchUsingPOSTParamsWithHTTPClient(client *http.Client) *ApplyProductPatchUsingPOSTParams {
	var ()
	return &ApplyProductPatchUsingPOSTParams{
		HTTPClient: client,
	}
}

/*ApplyProductPatchUsingPOSTParams contains all the parameters to send to the API endpoint
for the apply product patch using p o s t operation typically these are written to a http.Request
*/
type ApplyProductPatchUsingPOSTParams struct {

	/*EnvironmentID
	  environmentId

	*/
	EnvironmentID string
	/*PatchID
	  patchId

	*/
	PatchID string
	/*ProductID
	  productId

	*/
	ProductID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) WithTimeout(timeout time.Duration) *ApplyProductPatchUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) WithContext(ctx context.Context) *ApplyProductPatchUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) WithHTTPClient(client *http.Client) *ApplyProductPatchUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) WithEnvironmentID(environmentID string) *ApplyProductPatchUsingPOSTParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WithPatchID adds the patchID to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) WithPatchID(patchID string) *ApplyProductPatchUsingPOSTParams {
	o.SetPatchID(patchID)
	return o
}

// SetPatchID adds the patchId to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) SetPatchID(patchID string) {
	o.PatchID = patchID
}

// WithProductID adds the productID to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) WithProductID(productID string) *ApplyProductPatchUsingPOSTParams {
	o.SetProductID(productID)
	return o
}

// SetProductID adds the productId to the apply product patch using p o s t params
func (o *ApplyProductPatchUsingPOSTParams) SetProductID(productID string) {
	o.ProductID = productID
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyProductPatchUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentId
	if err := r.SetPathParam("environmentId", o.EnvironmentID); err != nil {
		return err
	}

	// path param patchId
	if err := r.SetPathParam("patchId", o.PatchID); err != nil {
		return err
	}

	// path param productId
	if err := r.SetPathParam("productId", o.ProductID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
