// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// ApplyProductPatchUsingPOSTReader is a Reader for the ApplyProductPatchUsingPOST structure.
type ApplyProductPatchUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplyProductPatchUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplyProductPatchUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewApplyProductPatchUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewApplyProductPatchUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewApplyProductPatchUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewApplyProductPatchUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewApplyProductPatchUsingPOSTOK creates a ApplyProductPatchUsingPOSTOK with default headers values
func NewApplyProductPatchUsingPOSTOK() *ApplyProductPatchUsingPOSTOK {
	return &ApplyProductPatchUsingPOSTOK{}
}

/*ApplyProductPatchUsingPOSTOK handles this case with default header values.

OK
*/
type ApplyProductPatchUsingPOSTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *ApplyProductPatchUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/patch/{patchId}][%d] applyProductPatchUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *ApplyProductPatchUsingPOSTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *ApplyProductPatchUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplyProductPatchUsingPOSTCreated creates a ApplyProductPatchUsingPOSTCreated with default headers values
func NewApplyProductPatchUsingPOSTCreated() *ApplyProductPatchUsingPOSTCreated {
	return &ApplyProductPatchUsingPOSTCreated{}
}

/*ApplyProductPatchUsingPOSTCreated handles this case with default header values.

Created
*/
type ApplyProductPatchUsingPOSTCreated struct {
}

func (o *ApplyProductPatchUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/patch/{patchId}][%d] applyProductPatchUsingPOSTCreated ", 201)
}

func (o *ApplyProductPatchUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewApplyProductPatchUsingPOSTUnauthorized creates a ApplyProductPatchUsingPOSTUnauthorized with default headers values
func NewApplyProductPatchUsingPOSTUnauthorized() *ApplyProductPatchUsingPOSTUnauthorized {
	return &ApplyProductPatchUsingPOSTUnauthorized{}
}

/*ApplyProductPatchUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type ApplyProductPatchUsingPOSTUnauthorized struct {
}

func (o *ApplyProductPatchUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/patch/{patchId}][%d] applyProductPatchUsingPOSTUnauthorized ", 401)
}

func (o *ApplyProductPatchUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewApplyProductPatchUsingPOSTForbidden creates a ApplyProductPatchUsingPOSTForbidden with default headers values
func NewApplyProductPatchUsingPOSTForbidden() *ApplyProductPatchUsingPOSTForbidden {
	return &ApplyProductPatchUsingPOSTForbidden{}
}

/*ApplyProductPatchUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type ApplyProductPatchUsingPOSTForbidden struct {
}

func (o *ApplyProductPatchUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/patch/{patchId}][%d] applyProductPatchUsingPOSTForbidden ", 403)
}

func (o *ApplyProductPatchUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewApplyProductPatchUsingPOSTNotFound creates a ApplyProductPatchUsingPOSTNotFound with default headers values
func NewApplyProductPatchUsingPOSTNotFound() *ApplyProductPatchUsingPOSTNotFound {
	return &ApplyProductPatchUsingPOSTNotFound{}
}

/*ApplyProductPatchUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type ApplyProductPatchUsingPOSTNotFound struct {
}

func (o *ApplyProductPatchUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/patch/{patchId}][%d] applyProductPatchUsingPOSTNotFound ", 404)
}

func (o *ApplyProductPatchUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
