// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateProductUpgradeRequestUsingPOSTReader is a Reader for the CreateProductUpgradeRequestUsingPOST structure.
type CreateProductUpgradeRequestUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProductUpgradeRequestUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProductUpgradeRequestUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewCreateProductUpgradeRequestUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateProductUpgradeRequestUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateProductUpgradeRequestUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateProductUpgradeRequestUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProductUpgradeRequestUsingPOSTOK creates a CreateProductUpgradeRequestUsingPOSTOK with default headers values
func NewCreateProductUpgradeRequestUsingPOSTOK() *CreateProductUpgradeRequestUsingPOSTOK {
	return &CreateProductUpgradeRequestUsingPOSTOK{}
}

/*CreateProductUpgradeRequestUsingPOSTOK handles this case with default header values.

OK
*/
type CreateProductUpgradeRequestUsingPOSTOK struct {
}

func (o *CreateProductUpgradeRequestUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/upgrade][%d] createProductUpgradeRequestUsingPOSTOK ", 200)
}

func (o *CreateProductUpgradeRequestUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateProductUpgradeRequestUsingPOSTCreated creates a CreateProductUpgradeRequestUsingPOSTCreated with default headers values
func NewCreateProductUpgradeRequestUsingPOSTCreated() *CreateProductUpgradeRequestUsingPOSTCreated {
	return &CreateProductUpgradeRequestUsingPOSTCreated{}
}

/*CreateProductUpgradeRequestUsingPOSTCreated handles this case with default header values.

Created
*/
type CreateProductUpgradeRequestUsingPOSTCreated struct {
}

func (o *CreateProductUpgradeRequestUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/upgrade][%d] createProductUpgradeRequestUsingPOSTCreated ", 201)
}

func (o *CreateProductUpgradeRequestUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateProductUpgradeRequestUsingPOSTUnauthorized creates a CreateProductUpgradeRequestUsingPOSTUnauthorized with default headers values
func NewCreateProductUpgradeRequestUsingPOSTUnauthorized() *CreateProductUpgradeRequestUsingPOSTUnauthorized {
	return &CreateProductUpgradeRequestUsingPOSTUnauthorized{}
}

/*CreateProductUpgradeRequestUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateProductUpgradeRequestUsingPOSTUnauthorized struct {
}

func (o *CreateProductUpgradeRequestUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/upgrade][%d] createProductUpgradeRequestUsingPOSTUnauthorized ", 401)
}

func (o *CreateProductUpgradeRequestUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateProductUpgradeRequestUsingPOSTForbidden creates a CreateProductUpgradeRequestUsingPOSTForbidden with default headers values
func NewCreateProductUpgradeRequestUsingPOSTForbidden() *CreateProductUpgradeRequestUsingPOSTForbidden {
	return &CreateProductUpgradeRequestUsingPOSTForbidden{}
}

/*CreateProductUpgradeRequestUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type CreateProductUpgradeRequestUsingPOSTForbidden struct {
}

func (o *CreateProductUpgradeRequestUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/upgrade][%d] createProductUpgradeRequestUsingPOSTForbidden ", 403)
}

func (o *CreateProductUpgradeRequestUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateProductUpgradeRequestUsingPOSTNotFound creates a CreateProductUpgradeRequestUsingPOSTNotFound with default headers values
func NewCreateProductUpgradeRequestUsingPOSTNotFound() *CreateProductUpgradeRequestUsingPOSTNotFound {
	return &CreateProductUpgradeRequestUsingPOSTNotFound{}
}

/*CreateProductUpgradeRequestUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type CreateProductUpgradeRequestUsingPOSTNotFound struct {
}

func (o *CreateProductUpgradeRequestUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/upgrade][%d] createProductUpgradeRequestUsingPOSTNotFound ", 404)
}

func (o *CreateProductUpgradeRequestUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
