// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// DeleteProductUsingGETReader is a Reader for the DeleteProductUsingGET structure.
type DeleteProductUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProductUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteProductUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteProductUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteProductUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteProductUsingGETOK creates a DeleteProductUsingGETOK with default headers values
func NewDeleteProductUsingGETOK() *DeleteProductUsingGETOK {
	return &DeleteProductUsingGETOK{}
}

/*DeleteProductUsingGETOK handles this case with default header values.

OK
*/
type DeleteProductUsingGETOK struct {
	Payload []*models.DeleteVMDetailsDTO
}

func (o *DeleteProductUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /lcm/lcops/api/environments/{environmentId}/products/{productId}/delete][%d] deleteProductUsingGETOK  %+v", 200, o.Payload)
}

func (o *DeleteProductUsingGETOK) GetPayload() []*models.DeleteVMDetailsDTO {
	return o.Payload
}

func (o *DeleteProductUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductUsingGETUnauthorized creates a DeleteProductUsingGETUnauthorized with default headers values
func NewDeleteProductUsingGETUnauthorized() *DeleteProductUsingGETUnauthorized {
	return &DeleteProductUsingGETUnauthorized{}
}

/*DeleteProductUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteProductUsingGETUnauthorized struct {
}

func (o *DeleteProductUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /lcm/lcops/api/environments/{environmentId}/products/{productId}/delete][%d] deleteProductUsingGETUnauthorized ", 401)
}

func (o *DeleteProductUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProductUsingGETForbidden creates a DeleteProductUsingGETForbidden with default headers values
func NewDeleteProductUsingGETForbidden() *DeleteProductUsingGETForbidden {
	return &DeleteProductUsingGETForbidden{}
}

/*DeleteProductUsingGETForbidden handles this case with default header values.

Forbidden
*/
type DeleteProductUsingGETForbidden struct {
}

func (o *DeleteProductUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /lcm/lcops/api/environments/{environmentId}/products/{productId}/delete][%d] deleteProductUsingGETForbidden ", 403)
}

func (o *DeleteProductUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProductUsingGETNotFound creates a DeleteProductUsingGETNotFound with default headers values
func NewDeleteProductUsingGETNotFound() *DeleteProductUsingGETNotFound {
	return &DeleteProductUsingGETNotFound{}
}

/*DeleteProductUsingGETNotFound handles this case with default header values.

Not Found
*/
type DeleteProductUsingGETNotFound struct {
}

func (o *DeleteProductUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /lcm/lcops/api/environments/{environmentId}/products/{productId}/delete][%d] deleteProductUsingGETNotFound ", 404)
}

func (o *DeleteProductUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
