// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadProductLogsUsingPOSTParams creates a new DownloadProductLogsUsingPOSTParams object
// with the default values initialized.
func NewDownloadProductLogsUsingPOSTParams() *DownloadProductLogsUsingPOSTParams {
	var ()
	return &DownloadProductLogsUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadProductLogsUsingPOSTParamsWithTimeout creates a new DownloadProductLogsUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDownloadProductLogsUsingPOSTParamsWithTimeout(timeout time.Duration) *DownloadProductLogsUsingPOSTParams {
	var ()
	return &DownloadProductLogsUsingPOSTParams{

		timeout: timeout,
	}
}

// NewDownloadProductLogsUsingPOSTParamsWithContext creates a new DownloadProductLogsUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewDownloadProductLogsUsingPOSTParamsWithContext(ctx context.Context) *DownloadProductLogsUsingPOSTParams {
	var ()
	return &DownloadProductLogsUsingPOSTParams{

		Context: ctx,
	}
}

// NewDownloadProductLogsUsingPOSTParamsWithHTTPClient creates a new DownloadProductLogsUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDownloadProductLogsUsingPOSTParamsWithHTTPClient(client *http.Client) *DownloadProductLogsUsingPOSTParams {
	var ()
	return &DownloadProductLogsUsingPOSTParams{
		HTTPClient: client,
	}
}

/*DownloadProductLogsUsingPOSTParams contains all the parameters to send to the API endpoint
for the download product logs using p o s t operation typically these are written to a http.Request
*/
type DownloadProductLogsUsingPOSTParams struct {

	/*EnvironmentID
	  environmentId

	*/
	EnvironmentID string
	/*ProductID
	  productId

	*/
	ProductID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) WithTimeout(timeout time.Duration) *DownloadProductLogsUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) WithContext(ctx context.Context) *DownloadProductLogsUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) WithHTTPClient(client *http.Client) *DownloadProductLogsUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) WithEnvironmentID(environmentID string) *DownloadProductLogsUsingPOSTParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WithProductID adds the productID to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) WithProductID(productID string) *DownloadProductLogsUsingPOSTParams {
	o.SetProductID(productID)
	return o
}

// SetProductID adds the productId to the download product logs using p o s t params
func (o *DownloadProductLogsUsingPOSTParams) SetProductID(productID string) {
	o.ProductID = productID
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadProductLogsUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentId
	if err := r.SetPathParam("environmentId", o.EnvironmentID); err != nil {
		return err
	}

	// path param productId
	if err := r.SetPathParam("productId", o.ProductID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
