// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// RevertProductSnapshotRequestUsingPOSTReader is a Reader for the RevertProductSnapshotRequestUsingPOST structure.
type RevertProductSnapshotRequestUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevertProductSnapshotRequestUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevertProductSnapshotRequestUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewRevertProductSnapshotRequestUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRevertProductSnapshotRequestUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRevertProductSnapshotRequestUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevertProductSnapshotRequestUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRevertProductSnapshotRequestUsingPOSTOK creates a RevertProductSnapshotRequestUsingPOSTOK with default headers values
func NewRevertProductSnapshotRequestUsingPOSTOK() *RevertProductSnapshotRequestUsingPOSTOK {
	return &RevertProductSnapshotRequestUsingPOSTOK{}
}

/*RevertProductSnapshotRequestUsingPOSTOK handles this case with default header values.

OK
*/
type RevertProductSnapshotRequestUsingPOSTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *RevertProductSnapshotRequestUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/revertsnapshot][%d] revertProductSnapshotRequestUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *RevertProductSnapshotRequestUsingPOSTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *RevertProductSnapshotRequestUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevertProductSnapshotRequestUsingPOSTCreated creates a RevertProductSnapshotRequestUsingPOSTCreated with default headers values
func NewRevertProductSnapshotRequestUsingPOSTCreated() *RevertProductSnapshotRequestUsingPOSTCreated {
	return &RevertProductSnapshotRequestUsingPOSTCreated{}
}

/*RevertProductSnapshotRequestUsingPOSTCreated handles this case with default header values.

Created
*/
type RevertProductSnapshotRequestUsingPOSTCreated struct {
}

func (o *RevertProductSnapshotRequestUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/revertsnapshot][%d] revertProductSnapshotRequestUsingPOSTCreated ", 201)
}

func (o *RevertProductSnapshotRequestUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevertProductSnapshotRequestUsingPOSTUnauthorized creates a RevertProductSnapshotRequestUsingPOSTUnauthorized with default headers values
func NewRevertProductSnapshotRequestUsingPOSTUnauthorized() *RevertProductSnapshotRequestUsingPOSTUnauthorized {
	return &RevertProductSnapshotRequestUsingPOSTUnauthorized{}
}

/*RevertProductSnapshotRequestUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type RevertProductSnapshotRequestUsingPOSTUnauthorized struct {
}

func (o *RevertProductSnapshotRequestUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/revertsnapshot][%d] revertProductSnapshotRequestUsingPOSTUnauthorized ", 401)
}

func (o *RevertProductSnapshotRequestUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevertProductSnapshotRequestUsingPOSTForbidden creates a RevertProductSnapshotRequestUsingPOSTForbidden with default headers values
func NewRevertProductSnapshotRequestUsingPOSTForbidden() *RevertProductSnapshotRequestUsingPOSTForbidden {
	return &RevertProductSnapshotRequestUsingPOSTForbidden{}
}

/*RevertProductSnapshotRequestUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type RevertProductSnapshotRequestUsingPOSTForbidden struct {
}

func (o *RevertProductSnapshotRequestUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/revertsnapshot][%d] revertProductSnapshotRequestUsingPOSTForbidden ", 403)
}

func (o *RevertProductSnapshotRequestUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevertProductSnapshotRequestUsingPOSTNotFound creates a RevertProductSnapshotRequestUsingPOSTNotFound with default headers values
func NewRevertProductSnapshotRequestUsingPOSTNotFound() *RevertProductSnapshotRequestUsingPOSTNotFound {
	return &RevertProductSnapshotRequestUsingPOSTNotFound{}
}

/*RevertProductSnapshotRequestUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type RevertProductSnapshotRequestUsingPOSTNotFound struct {
}

func (o *RevertProductSnapshotRequestUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/revertsnapshot][%d] revertProductSnapshotRequestUsingPOSTNotFound ", 404)
}

func (o *RevertProductSnapshotRequestUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
