// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// SyncProductIntegrationsUsingPOSTReader is a Reader for the SyncProductIntegrationsUsingPOST structure.
type SyncProductIntegrationsUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SyncProductIntegrationsUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSyncProductIntegrationsUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewSyncProductIntegrationsUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSyncProductIntegrationsUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSyncProductIntegrationsUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSyncProductIntegrationsUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSyncProductIntegrationsUsingPOSTOK creates a SyncProductIntegrationsUsingPOSTOK with default headers values
func NewSyncProductIntegrationsUsingPOSTOK() *SyncProductIntegrationsUsingPOSTOK {
	return &SyncProductIntegrationsUsingPOSTOK{}
}

/*SyncProductIntegrationsUsingPOSTOK handles this case with default header values.

OK
*/
type SyncProductIntegrationsUsingPOSTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *SyncProductIntegrationsUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/inventorysync][%d] syncProductIntegrationsUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *SyncProductIntegrationsUsingPOSTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *SyncProductIntegrationsUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSyncProductIntegrationsUsingPOSTCreated creates a SyncProductIntegrationsUsingPOSTCreated with default headers values
func NewSyncProductIntegrationsUsingPOSTCreated() *SyncProductIntegrationsUsingPOSTCreated {
	return &SyncProductIntegrationsUsingPOSTCreated{}
}

/*SyncProductIntegrationsUsingPOSTCreated handles this case with default header values.

Created
*/
type SyncProductIntegrationsUsingPOSTCreated struct {
}

func (o *SyncProductIntegrationsUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/inventorysync][%d] syncProductIntegrationsUsingPOSTCreated ", 201)
}

func (o *SyncProductIntegrationsUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSyncProductIntegrationsUsingPOSTUnauthorized creates a SyncProductIntegrationsUsingPOSTUnauthorized with default headers values
func NewSyncProductIntegrationsUsingPOSTUnauthorized() *SyncProductIntegrationsUsingPOSTUnauthorized {
	return &SyncProductIntegrationsUsingPOSTUnauthorized{}
}

/*SyncProductIntegrationsUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type SyncProductIntegrationsUsingPOSTUnauthorized struct {
}

func (o *SyncProductIntegrationsUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/inventorysync][%d] syncProductIntegrationsUsingPOSTUnauthorized ", 401)
}

func (o *SyncProductIntegrationsUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSyncProductIntegrationsUsingPOSTForbidden creates a SyncProductIntegrationsUsingPOSTForbidden with default headers values
func NewSyncProductIntegrationsUsingPOSTForbidden() *SyncProductIntegrationsUsingPOSTForbidden {
	return &SyncProductIntegrationsUsingPOSTForbidden{}
}

/*SyncProductIntegrationsUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type SyncProductIntegrationsUsingPOSTForbidden struct {
}

func (o *SyncProductIntegrationsUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/inventorysync][%d] syncProductIntegrationsUsingPOSTForbidden ", 403)
}

func (o *SyncProductIntegrationsUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSyncProductIntegrationsUsingPOSTNotFound creates a SyncProductIntegrationsUsingPOSTNotFound with default headers values
func NewSyncProductIntegrationsUsingPOSTNotFound() *SyncProductIntegrationsUsingPOSTNotFound {
	return &SyncProductIntegrationsUsingPOSTNotFound{}
}

/*SyncProductIntegrationsUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type SyncProductIntegrationsUsingPOSTNotFound struct {
}

func (o *SyncProductIntegrationsUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/products/{productId}/inventorysync][%d] syncProductIntegrationsUsingPOSTNotFound ", 404)
}

func (o *SyncProductIntegrationsUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
