// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// NewUpdateProductAdminPasswordRequestUsingPOSTParams creates a new UpdateProductAdminPasswordRequestUsingPOSTParams object
// with the default values initialized.
func NewUpdateProductAdminPasswordRequestUsingPOSTParams() *UpdateProductAdminPasswordRequestUsingPOSTParams {
	var ()
	return &UpdateProductAdminPasswordRequestUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProductAdminPasswordRequestUsingPOSTParamsWithTimeout creates a new UpdateProductAdminPasswordRequestUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateProductAdminPasswordRequestUsingPOSTParamsWithTimeout(timeout time.Duration) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	var ()
	return &UpdateProductAdminPasswordRequestUsingPOSTParams{

		timeout: timeout,
	}
}

// NewUpdateProductAdminPasswordRequestUsingPOSTParamsWithContext creates a new UpdateProductAdminPasswordRequestUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateProductAdminPasswordRequestUsingPOSTParamsWithContext(ctx context.Context) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	var ()
	return &UpdateProductAdminPasswordRequestUsingPOSTParams{

		Context: ctx,
	}
}

// NewUpdateProductAdminPasswordRequestUsingPOSTParamsWithHTTPClient creates a new UpdateProductAdminPasswordRequestUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateProductAdminPasswordRequestUsingPOSTParamsWithHTTPClient(client *http.Client) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	var ()
	return &UpdateProductAdminPasswordRequestUsingPOSTParams{
		HTTPClient: client,
	}
}

/*UpdateProductAdminPasswordRequestUsingPOSTParams contains all the parameters to send to the API endpoint
for the update product admin password request using p o s t operation typically these are written to a http.Request
*/
type UpdateProductAdminPasswordRequestUsingPOSTParams struct {

	/*EnvironmentID
	  environmentId

	*/
	EnvironmentID string
	/*ProductID
	  productId

	*/
	ProductID string
	/*UpdateAdminPasswordRequestDTO
	  updateAdminPasswordRequestDTO

	*/
	UpdateAdminPasswordRequestDTO *models.UpdateAdminPasswordRequestDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WithTimeout(timeout time.Duration) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WithContext(ctx context.Context) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WithHTTPClient(client *http.Client) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentID adds the environmentID to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WithEnvironmentID(environmentID string) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) SetEnvironmentID(environmentID string) {
	o.EnvironmentID = environmentID
}

// WithProductID adds the productID to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WithProductID(productID string) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	o.SetProductID(productID)
	return o
}

// SetProductID adds the productId to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) SetProductID(productID string) {
	o.ProductID = productID
}

// WithUpdateAdminPasswordRequestDTO adds the updateAdminPasswordRequestDTO to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WithUpdateAdminPasswordRequestDTO(updateAdminPasswordRequestDTO *models.UpdateAdminPasswordRequestDTO) *UpdateProductAdminPasswordRequestUsingPOSTParams {
	o.SetUpdateAdminPasswordRequestDTO(updateAdminPasswordRequestDTO)
	return o
}

// SetUpdateAdminPasswordRequestDTO adds the updateAdminPasswordRequestDTO to the update product admin password request using p o s t params
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) SetUpdateAdminPasswordRequestDTO(updateAdminPasswordRequestDTO *models.UpdateAdminPasswordRequestDTO) {
	o.UpdateAdminPasswordRequestDTO = updateAdminPasswordRequestDTO
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProductAdminPasswordRequestUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentId
	if err := r.SetPathParam("environmentId", o.EnvironmentID); err != nil {
		return err
	}

	// path param productId
	if err := r.SetPathParam("productId", o.ProductID); err != nil {
		return err
	}

	if o.UpdateAdminPasswordRequestDTO != nil {
		if err := r.SetBodyParam(o.UpdateAdminPasswordRequestDTO); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
