// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// ValidateProductScaleoutOvaMappedRequestUsingPOSTReader is a Reader for the ValidateProductScaleoutOvaMappedRequestUsingPOST structure.
type ValidateProductScaleoutOvaMappedRequestUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateProductScaleoutOvaMappedRequestUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewValidateProductScaleoutOvaMappedRequestUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewValidateProductScaleoutOvaMappedRequestUsingPOSTOK creates a ValidateProductScaleoutOvaMappedRequestUsingPOSTOK with default headers values
func NewValidateProductScaleoutOvaMappedRequestUsingPOSTOK() *ValidateProductScaleoutOvaMappedRequestUsingPOSTOK {
	return &ValidateProductScaleoutOvaMappedRequestUsingPOSTOK{}
}

/*ValidateProductScaleoutOvaMappedRequestUsingPOSTOK handles this case with default header values.

OK
*/
type ValidateProductScaleoutOvaMappedRequestUsingPOSTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/product/scaleout/validate][%d] validateProductScaleoutOvaMappedRequestUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateProductScaleoutOvaMappedRequestUsingPOSTCreated creates a ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated with default headers values
func NewValidateProductScaleoutOvaMappedRequestUsingPOSTCreated() *ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated {
	return &ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated{}
}

/*ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated handles this case with default header values.

Created
*/
type ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated struct {
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/product/scaleout/validate][%d] validateProductScaleoutOvaMappedRequestUsingPOSTCreated ", 201)
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized creates a ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized with default headers values
func NewValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized() *ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized {
	return &ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized{}
}

/*ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized struct {
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/product/scaleout/validate][%d] validateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized ", 401)
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden creates a ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden with default headers values
func NewValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden() *ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden {
	return &ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden{}
}

/*ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden struct {
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/product/scaleout/validate][%d] validateProductScaleoutOvaMappedRequestUsingPOSTForbidden ", 403)
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound creates a ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound with default headers values
func NewValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound() *ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound {
	return &ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound{}
}

/*ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound struct {
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/product/scaleout/validate][%d] validateProductScaleoutOvaMappedRequestUsingPOSTNotFound ", 404)
}

func (o *ValidateProductScaleoutOvaMappedRequestUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
