// Code generated by go-swagger; DO NOT EDIT.

package deployments_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// VropsApuatIntegrationsUsingPOSTReader is a Reader for the VropsApuatIntegrationsUsingPOST structure.
type VropsApuatIntegrationsUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VropsApuatIntegrationsUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVropsApuatIntegrationsUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewVropsApuatIntegrationsUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewVropsApuatIntegrationsUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewVropsApuatIntegrationsUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewVropsApuatIntegrationsUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewVropsApuatIntegrationsUsingPOSTOK creates a VropsApuatIntegrationsUsingPOSTOK with default headers values
func NewVropsApuatIntegrationsUsingPOSTOK() *VropsApuatIntegrationsUsingPOSTOK {
	return &VropsApuatIntegrationsUsingPOSTOK{}
}

/*VropsApuatIntegrationsUsingPOSTOK handles this case with default header values.

OK
*/
type VropsApuatIntegrationsUsingPOSTOK struct {
	Payload *models.GenericRequestResponse
}

func (o *VropsApuatIntegrationsUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/upgradeVersion/{upgradeVersion}/vropsapuat][%d] vropsApuatIntegrationsUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *VropsApuatIntegrationsUsingPOSTOK) GetPayload() *models.GenericRequestResponse {
	return o.Payload
}

func (o *VropsApuatIntegrationsUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVropsApuatIntegrationsUsingPOSTCreated creates a VropsApuatIntegrationsUsingPOSTCreated with default headers values
func NewVropsApuatIntegrationsUsingPOSTCreated() *VropsApuatIntegrationsUsingPOSTCreated {
	return &VropsApuatIntegrationsUsingPOSTCreated{}
}

/*VropsApuatIntegrationsUsingPOSTCreated handles this case with default header values.

Created
*/
type VropsApuatIntegrationsUsingPOSTCreated struct {
}

func (o *VropsApuatIntegrationsUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/upgradeVersion/{upgradeVersion}/vropsapuat][%d] vropsApuatIntegrationsUsingPOSTCreated ", 201)
}

func (o *VropsApuatIntegrationsUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVropsApuatIntegrationsUsingPOSTUnauthorized creates a VropsApuatIntegrationsUsingPOSTUnauthorized with default headers values
func NewVropsApuatIntegrationsUsingPOSTUnauthorized() *VropsApuatIntegrationsUsingPOSTUnauthorized {
	return &VropsApuatIntegrationsUsingPOSTUnauthorized{}
}

/*VropsApuatIntegrationsUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type VropsApuatIntegrationsUsingPOSTUnauthorized struct {
}

func (o *VropsApuatIntegrationsUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/upgradeVersion/{upgradeVersion}/vropsapuat][%d] vropsApuatIntegrationsUsingPOSTUnauthorized ", 401)
}

func (o *VropsApuatIntegrationsUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVropsApuatIntegrationsUsingPOSTForbidden creates a VropsApuatIntegrationsUsingPOSTForbidden with default headers values
func NewVropsApuatIntegrationsUsingPOSTForbidden() *VropsApuatIntegrationsUsingPOSTForbidden {
	return &VropsApuatIntegrationsUsingPOSTForbidden{}
}

/*VropsApuatIntegrationsUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type VropsApuatIntegrationsUsingPOSTForbidden struct {
}

func (o *VropsApuatIntegrationsUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/upgradeVersion/{upgradeVersion}/vropsapuat][%d] vropsApuatIntegrationsUsingPOSTForbidden ", 403)
}

func (o *VropsApuatIntegrationsUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVropsApuatIntegrationsUsingPOSTNotFound creates a VropsApuatIntegrationsUsingPOSTNotFound with default headers values
func NewVropsApuatIntegrationsUsingPOSTNotFound() *VropsApuatIntegrationsUsingPOSTNotFound {
	return &VropsApuatIntegrationsUsingPOSTNotFound{}
}

/*VropsApuatIntegrationsUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type VropsApuatIntegrationsUsingPOSTNotFound struct {
}

func (o *VropsApuatIntegrationsUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /lcm/lcops/api/environments/{environmentId}/upgradeVersion/{upgradeVersion}/vropsapuat][%d] vropsApuatIntegrationsUsingPOSTNotFound ", 404)
}

func (o *VropsApuatIntegrationsUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
