// Code generated by go-swagger; DO NOT EDIT.

package command_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAllCommandsUsingDELETEParams creates a new DeleteAllCommandsUsingDELETEParams object
// with the default values initialized.
func NewDeleteAllCommandsUsingDELETEParams() *DeleteAllCommandsUsingDELETEParams {

	return &DeleteAllCommandsUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAllCommandsUsingDELETEParamsWithTimeout creates a new DeleteAllCommandsUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAllCommandsUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteAllCommandsUsingDELETEParams {

	return &DeleteAllCommandsUsingDELETEParams{

		timeout: timeout,
	}
}

// NewDeleteAllCommandsUsingDELETEParamsWithContext creates a new DeleteAllCommandsUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAllCommandsUsingDELETEParamsWithContext(ctx context.Context) *DeleteAllCommandsUsingDELETEParams {

	return &DeleteAllCommandsUsingDELETEParams{

		Context: ctx,
	}
}

// NewDeleteAllCommandsUsingDELETEParamsWithHTTPClient creates a new DeleteAllCommandsUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAllCommandsUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteAllCommandsUsingDELETEParams {

	return &DeleteAllCommandsUsingDELETEParams{
		HTTPClient: client,
	}
}

/*DeleteAllCommandsUsingDELETEParams contains all the parameters to send to the API endpoint
for the delete all commands using d e l e t e operation typically these are written to a http.Request
*/
type DeleteAllCommandsUsingDELETEParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete all commands using d e l e t e params
func (o *DeleteAllCommandsUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteAllCommandsUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete all commands using d e l e t e params
func (o *DeleteAllCommandsUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete all commands using d e l e t e params
func (o *DeleteAllCommandsUsingDELETEParams) WithContext(ctx context.Context) *DeleteAllCommandsUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete all commands using d e l e t e params
func (o *DeleteAllCommandsUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete all commands using d e l e t e params
func (o *DeleteAllCommandsUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteAllCommandsUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete all commands using d e l e t e params
func (o *DeleteAllCommandsUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAllCommandsUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
