// Code generated by go-swagger; DO NOT EDIT.

package command_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// GetAllCommandsUsingPOSTReader is a Reader for the GetAllCommandsUsingPOST structure.
type GetAllCommandsUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllCommandsUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllCommandsUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewGetAllCommandsUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAllCommandsUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAllCommandsUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllCommandsUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllCommandsUsingPOSTOK creates a GetAllCommandsUsingPOSTOK with default headers values
func NewGetAllCommandsUsingPOSTOK() *GetAllCommandsUsingPOSTOK {
	return &GetAllCommandsUsingPOSTOK{}
}

/*GetAllCommandsUsingPOSTOK handles this case with default header values.

OK
*/
type GetAllCommandsUsingPOSTOK struct {
	Payload []*models.CommandInfoObject
}

func (o *GetAllCommandsUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /command/get/all][%d] getAllCommandsUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *GetAllCommandsUsingPOSTOK) GetPayload() []*models.CommandInfoObject {
	return o.Payload
}

func (o *GetAllCommandsUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllCommandsUsingPOSTCreated creates a GetAllCommandsUsingPOSTCreated with default headers values
func NewGetAllCommandsUsingPOSTCreated() *GetAllCommandsUsingPOSTCreated {
	return &GetAllCommandsUsingPOSTCreated{}
}

/*GetAllCommandsUsingPOSTCreated handles this case with default header values.

Created
*/
type GetAllCommandsUsingPOSTCreated struct {
}

func (o *GetAllCommandsUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /command/get/all][%d] getAllCommandsUsingPOSTCreated ", 201)
}

func (o *GetAllCommandsUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllCommandsUsingPOSTUnauthorized creates a GetAllCommandsUsingPOSTUnauthorized with default headers values
func NewGetAllCommandsUsingPOSTUnauthorized() *GetAllCommandsUsingPOSTUnauthorized {
	return &GetAllCommandsUsingPOSTUnauthorized{}
}

/*GetAllCommandsUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAllCommandsUsingPOSTUnauthorized struct {
}

func (o *GetAllCommandsUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /command/get/all][%d] getAllCommandsUsingPOSTUnauthorized ", 401)
}

func (o *GetAllCommandsUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllCommandsUsingPOSTForbidden creates a GetAllCommandsUsingPOSTForbidden with default headers values
func NewGetAllCommandsUsingPOSTForbidden() *GetAllCommandsUsingPOSTForbidden {
	return &GetAllCommandsUsingPOSTForbidden{}
}

/*GetAllCommandsUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type GetAllCommandsUsingPOSTForbidden struct {
}

func (o *GetAllCommandsUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /command/get/all][%d] getAllCommandsUsingPOSTForbidden ", 403)
}

func (o *GetAllCommandsUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllCommandsUsingPOSTNotFound creates a GetAllCommandsUsingPOSTNotFound with default headers values
func NewGetAllCommandsUsingPOSTNotFound() *GetAllCommandsUsingPOSTNotFound {
	return &GetAllCommandsUsingPOSTNotFound{}
}

/*GetAllCommandsUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type GetAllCommandsUsingPOSTNotFound struct {
}

func (o *GetAllCommandsUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /command/get/all][%d] getAllCommandsUsingPOSTNotFound ", 404)
}

func (o *GetAllCommandsUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
