// Code generated by go-swagger; DO NOT EDIT.

package authzn_sample_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// WhoAmIUsingGETReader is a Reader for the WhoAmIUsingGET structure.
type WhoAmIUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WhoAmIUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWhoAmIUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWhoAmIUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewWhoAmIUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewWhoAmIUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWhoAmIUsingGETOK creates a WhoAmIUsingGETOK with default headers values
func NewWhoAmIUsingGETOK() *WhoAmIUsingGETOK {
	return &WhoAmIUsingGETOK{}
}

/*WhoAmIUsingGETOK handles this case with default header values.

OK
*/
type WhoAmIUsingGETOK struct {
	Payload *models.AuthenticatedUserDTO
}

func (o *WhoAmIUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/me][%d] whoAmIUsingGETOK  %+v", 200, o.Payload)
}

func (o *WhoAmIUsingGETOK) GetPayload() *models.AuthenticatedUserDTO {
	return o.Payload
}

func (o *WhoAmIUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticatedUserDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWhoAmIUsingGETUnauthorized creates a WhoAmIUsingGETUnauthorized with default headers values
func NewWhoAmIUsingGETUnauthorized() *WhoAmIUsingGETUnauthorized {
	return &WhoAmIUsingGETUnauthorized{}
}

/*WhoAmIUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type WhoAmIUsingGETUnauthorized struct {
}

func (o *WhoAmIUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/me][%d] whoAmIUsingGETUnauthorized ", 401)
}

func (o *WhoAmIUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWhoAmIUsingGETForbidden creates a WhoAmIUsingGETForbidden with default headers values
func NewWhoAmIUsingGETForbidden() *WhoAmIUsingGETForbidden {
	return &WhoAmIUsingGETForbidden{}
}

/*WhoAmIUsingGETForbidden handles this case with default header values.

Forbidden
*/
type WhoAmIUsingGETForbidden struct {
}

func (o *WhoAmIUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/me][%d] whoAmIUsingGETForbidden ", 403)
}

func (o *WhoAmIUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWhoAmIUsingGETNotFound creates a WhoAmIUsingGETNotFound with default headers values
func NewWhoAmIUsingGETNotFound() *WhoAmIUsingGETNotFound {
	return &WhoAmIUsingGETNotFound{}
}

/*WhoAmIUsingGETNotFound handles this case with default header values.

Not Found
*/
type WhoAmIUsingGETNotFound struct {
}

func (o *WhoAmIUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /lcm/authzn/api/me][%d] whoAmIUsingGETNotFound ", 404)
}

func (o *WhoAmIUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
