// Code generated by go-swagger; DO NOT EDIT.

package health_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLcmHealthStatusUsingGETParams creates a new GetLcmHealthStatusUsingGETParams object
// with the default values initialized.
func NewGetLcmHealthStatusUsingGETParams() *GetLcmHealthStatusUsingGETParams {

	return &GetLcmHealthStatusUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLcmHealthStatusUsingGETParamsWithTimeout creates a new GetLcmHealthStatusUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLcmHealthStatusUsingGETParamsWithTimeout(timeout time.Duration) *GetLcmHealthStatusUsingGETParams {

	return &GetLcmHealthStatusUsingGETParams{

		timeout: timeout,
	}
}

// NewGetLcmHealthStatusUsingGETParamsWithContext creates a new GetLcmHealthStatusUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLcmHealthStatusUsingGETParamsWithContext(ctx context.Context) *GetLcmHealthStatusUsingGETParams {

	return &GetLcmHealthStatusUsingGETParams{

		Context: ctx,
	}
}

// NewGetLcmHealthStatusUsingGETParamsWithHTTPClient creates a new GetLcmHealthStatusUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLcmHealthStatusUsingGETParamsWithHTTPClient(client *http.Client) *GetLcmHealthStatusUsingGETParams {

	return &GetLcmHealthStatusUsingGETParams{
		HTTPClient: client,
	}
}

/*GetLcmHealthStatusUsingGETParams contains all the parameters to send to the API endpoint
for the get lcm health status using g e t operation typically these are written to a http.Request
*/
type GetLcmHealthStatusUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lcm health status using g e t params
func (o *GetLcmHealthStatusUsingGETParams) WithTimeout(timeout time.Duration) *GetLcmHealthStatusUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lcm health status using g e t params
func (o *GetLcmHealthStatusUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lcm health status using g e t params
func (o *GetLcmHealthStatusUsingGETParams) WithContext(ctx context.Context) *GetLcmHealthStatusUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lcm health status using g e t params
func (o *GetLcmHealthStatusUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lcm health status using g e t params
func (o *GetLcmHealthStatusUsingGETParams) WithHTTPClient(client *http.Client) *GetLcmHealthStatusUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lcm health status using g e t params
func (o *GetLcmHealthStatusUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLcmHealthStatusUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
