// Code generated by go-swagger; DO NOT EDIT.

package health_a_p_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cars/terraform-provider-vrlcm/models"
)

// GetLcmHealthStatusUsingGETReader is a Reader for the GetLcmHealthStatusUsingGET structure.
type GetLcmHealthStatusUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLcmHealthStatusUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLcmHealthStatusUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLcmHealthStatusUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetLcmHealthStatusUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLcmHealthStatusUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLcmHealthStatusUsingGETOK creates a GetLcmHealthStatusUsingGETOK with default headers values
func NewGetLcmHealthStatusUsingGETOK() *GetLcmHealthStatusUsingGETOK {
	return &GetLcmHealthStatusUsingGETOK{}
}

/*GetLcmHealthStatusUsingGETOK handles this case with default header values.

OK
*/
type GetLcmHealthStatusUsingGETOK struct {
	Payload *models.LcmHealthStatusDTO
}

func (o *GetLcmHealthStatusUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /lcm/health/api/status][%d] getLcmHealthStatusUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetLcmHealthStatusUsingGETOK) GetPayload() *models.LcmHealthStatusDTO {
	return o.Payload
}

func (o *GetLcmHealthStatusUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LcmHealthStatusDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLcmHealthStatusUsingGETUnauthorized creates a GetLcmHealthStatusUsingGETUnauthorized with default headers values
func NewGetLcmHealthStatusUsingGETUnauthorized() *GetLcmHealthStatusUsingGETUnauthorized {
	return &GetLcmHealthStatusUsingGETUnauthorized{}
}

/*GetLcmHealthStatusUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetLcmHealthStatusUsingGETUnauthorized struct {
}

func (o *GetLcmHealthStatusUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /lcm/health/api/status][%d] getLcmHealthStatusUsingGETUnauthorized ", 401)
}

func (o *GetLcmHealthStatusUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLcmHealthStatusUsingGETForbidden creates a GetLcmHealthStatusUsingGETForbidden with default headers values
func NewGetLcmHealthStatusUsingGETForbidden() *GetLcmHealthStatusUsingGETForbidden {
	return &GetLcmHealthStatusUsingGETForbidden{}
}

/*GetLcmHealthStatusUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetLcmHealthStatusUsingGETForbidden struct {
}

func (o *GetLcmHealthStatusUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /lcm/health/api/status][%d] getLcmHealthStatusUsingGETForbidden ", 403)
}

func (o *GetLcmHealthStatusUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLcmHealthStatusUsingGETNotFound creates a GetLcmHealthStatusUsingGETNotFound with default headers values
func NewGetLcmHealthStatusUsingGETNotFound() *GetLcmHealthStatusUsingGETNotFound {
	return &GetLcmHealthStatusUsingGETNotFound{}
}

/*GetLcmHealthStatusUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetLcmHealthStatusUsingGETNotFound struct {
}

func (o *GetLcmHealthStatusUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /lcm/health/api/status][%d] getLcmHealthStatusUsingGETNotFound ", 404)
}

func (o *GetLcmHealthStatusUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
